### PR TITLE
Session: Add sesion general funcs

### LINKED ISSUE #593: [BUG] Snowflake Function: current_version
**Function:** `current_version`
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_version

**Test SQL:**
```sql
SELECT CURRENT_VERSION();
```

**Expected Result:**
```
Snowflake version string
```

**Actual Result:**
```
SELECT CURRENT_VERSION();
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_version'.                                                                   │
│ Did you mean 'current_time'?                                                                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### LINKED ISSUE #666: [BUG] Missing function: current_role_type
**Function:** `current_role_type`
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_role_type

**Test SQL:**
```sql
SELECT CURRENT_ROLE_TYPE();
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT CURRENT_ROLE_TYPE();
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_role_type'.                  │
│ Did you mean 'current_date'?                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### PR DESCRIPTION
**Pull request by osipovartem**
- current_version (version of core-executor crate)
- current_client (version of core-executor crate with Embucket prefix)
- current_role_type - just default since we don't support roles (ROLE according to snowflake)
- current_role - just default since we don't support roles

Added macros for df-builtins insta tests (we don't need UserSession for most of queries)

Closes #593  + current_client()
Closes #666  + current_role()
Related to #934

### CODE REVIEW

**Review by DanCodedThis — DISMISSED** [review]
LGTM

File: crates/df-builtins/src/session/mod.rs [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+}
+
+/// Returns the name of the warehouse in use for the current session.
+fn current_warehouse_udf() -> ScalarUDF {
+    create_session_context_udf!("current_warehouse", "default")
+}
+
+/// Returns the current Embucket version.
+fn current_version_udf() -> ScalarUDF {
+    create_session_context_udf!("current_version", env!("CARGO_PKG_VERSION"))
```
Comment (Vedin) [inline crates/df-builtins/src/session/mod.rs:38]: what's `CARGO_PKG_VERSION` here? As I understood it's pkg version. In this context will it be version of `df-builtins`? We don't have any version for embucket as I can see in main `Cargo.toml`

File: crates/df-builtins/src/tests/query.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
+use crate::test_query;
+
+// Session context
+test_query!(
```
Comment (Vedin) [inline crates/df-builtins/src/tests/query.rs:4]: Don't we already have this test in previous PR?

File: crates/df-builtins/src/session/mod.rs (hunk 1 above)
Comment (osipovartem) [reply crates/df-builtins/src/session/mod.rs:38]: Here we will see df-buildins version
[package]
name = "df-builtins"
**version = "0.1.0"**
edition = "2024"
license-file.workspace = true
For core-executor we will see core-executor crate cargo version

File: crates/df-builtins/src/tests/query.rs (hunk 2 above)
Comment (osipovartem) [reply crates/df-builtins/src/tests/query.rs:4]: This is a raw udfs tests
In core-executor crate we have tests **after logical plan rewriter** since we override scalar values from initial udf state

**Review by Vedin — APPROVED** [review]
lgtm! I'd only suggest to create an issue to create a embucket version in embucket Cargo.toml and expose it here.
