### PR TITLE
Move qualify to visitor with common_sub_expression_eliminate rule fix 

### LINKED ISSUE #1154: [BUG] Optimizer rule 'common_sub_expression_eliminate' failed due to window has mismatch between number of expressions (1) and number of fields in schema (0)
**NOTE: The problem mith be in qualify**

```sql
SELECT *
FROM embucket.tap_postgres.gitlab_db_bulk_import_entities
WHERE _task_instance = (SELECT MAX(_task_instance) AS max_column_value FROM embucket.tap_postgres.gitlab_db_bulk_import_entities)
QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY _uploaded_at DESC) = 1
```

`Query execution error: Query execution error: DataFusion error: Optimizer rule 'common_sub_expression_eliminate' failed caused by Error during planning: Window has mismatch between number of expressions (1) and number of fields in schema (0) 0: <transparent> 1: Query execution error: Query execution error: DataFusion error: Optimizer rule 'common_sub_expression_eliminate' failed caused by Error during planning: Window has mismatch between number of expressions (1) and number of fields in schema (0), at crates/api-ui/src/queries/handlers.rs:118:10 2: Query execution error: DataFusion error: Optimizer rule 'common_sub_expression_eliminate' failed caused by Error during planning: Window has mismatch between number of expressions (1) and number of fields in schema (0), at crates/api-ui/src/queries/handlers.rs:117:10 3: DataFusion error: Optimizer rule 'common_sub_expression_eliminate' failed caused by Error during planning: Window has mismatch between number of expressions (1) and number of fields in schema (0), at crates/core-executor/src/query.rs:1377:22 4: Context("Optimizer rule 'common_sub_expression_eliminate' failed", Plan("Window has mismatch between number of expressions (1) and number of fields in schema (0)"))
`

### PR DESCRIPTION
**Pull request by osipovartem**
This pull request introduces a new qualify_in_query, to handle `QUALIFY` clauses in SQL queries. It refactors the existing query processing logic to replace an inline implementation with this modular approach, improving maintainability and testability. Additionally, it includes a new test case to validate the behavior of the `qualify_in_query` visitor.

Closes #1154

### CODE REVIEW

File: crates/embucket-functions/src/visitors/qualify_in_query.rs [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+};
+use datafusion::sql::sqlparser::ast::{Expr, Query, SetExpr};
+use datafusion_expr::sqlparser::ast::VisitMut;
+use datafusion_expr::sqlparser::ast::{Statement, VisitorMut};
+use std::ops::ControlFlow;
+
+/// Visitor that converts BINARY and VARBINARY types to BYTEA in CREATE TABLE statements
+///
+/// This allows `DataFusion` to support standard SQL BINARY types by converting them to
+/// the supported BYTEA type, which maps to `DataType::Binary` internally.
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/visitors/qualify_in_query.rs]: Inccorect comment?

**Review by DanCodedThis — APPROVED** [review]
LGTM

**Review by rampage644 — APPROVED** [review]
