### PR TITLE
Show* statements should return error for missing db/schema/table

### LINKED ISSUE #1581: SHOW SCHEMAS IN DATABASE returns wrong database schemas when target database doesn't exist
## Problem

When executing `SHOW TERSE SCHEMAS IN DATABASE "nosuchdatabase"` with a non-existent database name, the query incorrectly returns schemas from the current database (`embucket`) instead of either:
1. Returning an error indicating the database doesn't exist
2. Returning empty results

## Expected Behavior

The query should either:
- Throw an error: "Database 'nosuchdatabase' does not exist"
- Return empty results if the database doesn't exist

## Actual Behavior

Returns schemas from the current database (`embucket`):
```
+----------------------------------------------------------------------------+
| created_on | name                     | kind | database_name | schema_name |
|------------+--------------------------+------+---------------+-------------|
| None       | public                   | None | embucket      | None        |
| None       | public_derived           | None | embucket      | None        |
| None       | public_scratch           | None | embucket      | None        |
| None       | public_snowplow_manifest | None | embucket      | None        |
| None       | information_schema       | None | embucket      | None        |
+----------------------------------------------------------------------------+
```

## Steps to Reproduce

1. Connect to any database
2. Execute: `SHOW TERSE SCHEMAS IN DATABASE "nosuchdatabase";`
3. Observe that schemas from the current database are returned instead of an error or empty result

### PR DESCRIPTION
**Pull request by osipovartem**
Closes #1581

Also moved some related tests to correct path

### CODE REVIEW

File: crates/core-executor/src/query.rs [hunk 1]
```diff
@@ -1830,26 +1835,107 @@ impl UserQuery {
...
+
+        let table_ref = match parent_type {
+            ShowType::Account | ShowType::Database => {
+                let database = parts.join("");
+                self.get_catalog(&database).map_err(|_| {
+                    ex_error::DatabaseNotFoundSnafu {
+                        db: database.clone(),
+                    }
+                    .build()
+                })?;
```
Comment (DanCodedThis) [inline crates/core-executor/src/query.rs]: This could be:
```rust
self.get_catalog(&database).context(ex_error::DatabaseNotFoundSnafu {
                        db: database.clone(),
                    })?;
```

File: crates/core-executor/src/query.rs [hunk 2]
```diff
@@ -1830,26 +1835,107 @@ impl UserQuery {
...
+                    [s] => (self.current_database(), s.clone()),
+                    [d, s] => (d.clone(), s.clone()),
+                    _ => (String::new(), String::new()),
+                };
+                let catalog = self.get_catalog(&database).map_err(|_| {
+                    ex_error::DatabaseNotFoundSnafu {
+                        db: database.clone(),
+                    }
+                    .build()
+                })?;
```
Comment (DanCodedThis) [inline crates/core-executor/src/query.rs]: Same here

File: crates/core-executor/src/query.rs [hunk 3]
```diff
@@ -1830,26 +1835,107 @@ impl UserQuery {
...
+                        self.current_schema(),
+                        String::new(),
+                    ),
+                };
+                let catalog = self.get_catalog(&database).map_err(|_| {
+                    ex_error::DatabaseNotFoundSnafu {
+                        db: database.clone(),
+                    }
+                    .build()
+                })?;
```
Comment (DanCodedThis) [inline crates/core-executor/src/query.rs]: Here also

**Review by DanCodedThis — APPROVED** [review]
@osipovartem LGTM, minor erroring nitpicks

File: crates/core-executor/src/query.rs (hunk 1 above)
Comment (osipovartem) [reply crates/core-executor/src/query.rs]: get_catalog already returns
```rust 
ex_error::CatalogNotFoundSnafu {
                    catalog: name.to_string(),
                }
                .build()
```
so we trying to send new error

**Review by DanCodedThis — APPROVED** [review]

**Review by rampage644 — APPROVED** [review]
