### PR TITLE
Issue/373 openapi payloads schemas and other

### LINKED ISSUE #373: api: For UI endpoints generate open api spec using separate createpayload, updatepayload schemas for handlers groups
* Get rid of IceBucket prefix in schema name of openapi spec.
* Do logical separation on open api spec level if possible, Or create separate schemas  and use in implementation.
* Separate Worksheet payloads for update, create
* Fix deploy error

### LINKED ISSUE #375: Registry issue when Cargo.lock removed
Reproducible here too:
https://github.com/Embucket/icebucket/actions/runs/13999038528/job/39387689107#step:4:41

```
cargo clean
     Removed 0 files
user@:~/git/icebucket$ cargo update
    Updating git repository `https://github.com/chronotope/chrono.git`
    Updating git repository `https://github.com/Embucket/datafusion.git`
    Updating crates.io index
    Updating git repository `https://github.com/Embucket/datafusion-functions-json.git`
    Updating git repository `https://github.com/Embucket/iceberg-rust.git`
    Updating git repository `https://github.com/geoarrow/geoarrow-rs.git`
    Updating git repository `https://github.com/Embucket/datafusion-sqlparser-rs.git`
    Updating git repository `https://github.com/hansetag/iceberg-rust.git`
    Updating git repository `https://github.com/twuebi/opendal.git`
    Updating git repository `https://github.com/twuebi/reqsign.git`
error: failed to select a version for `i_float`.
    ... required by package `i_overlay v2.0.0`
    ... which satisfies dependency `i_overlay = "^2.0.0, <2.1.0"` of package `geo v0.30.0`
    ... which satisfies dependency `geo = "^0.30"` of package `geodatafusion v0.1.0-dev (https://github.com/geoarrow/geoarrow-rs.git#c7bb1f40)`
    ... which satisfies git dependency `geodatafusion` of package `icebucket_runtime v0.1.0 (/home/yaroslav/git/icebucket/crates/runtime)`
    ... which satisfies path dependency `icebucket_runtime` of package `bucketd v0.1.0 (/home/yaroslav/git/icebucket/bin/bucketd)`
versions that meet the requirements `~1.7.0` are: 1.7.0

all possible versions conflict with previously selected packages.

  previously selected package `i_float v1.5.0`
    ... which satisfies dependency `i_float = "~1.5.0"` of package `i_overlay v1.9.0`
    ... which satisfies dependency `i_overlay = "^1.9.0, <1.10.0"` of package `geo v0.29.3`
    ... which satisfies dependency `geo = "^0.29.3"` of package `geoarrow v0.4.0-beta.4`
    ... which satisfies dependency `geoarrow = "^0.4.0-beta.4"` of package `icebucket_runtime v0.1.0 (/home/yaroslav/git/icebucket/crates/runtime)`
    ... which satisfies path dependency `icebucket_runtime` of package `bucketd v0.1.0 (/home/yaroslav/git/icebucket/bin/bucketd)`

failed to select a version for `i_float` which could resolve this conflict
```

### PR DESCRIPTION
**Pull request by YaroslavLitvinov**
closes #375
not yet #373

- [x] Get rid of IceBucket prefix in schema name of openapi spec.
- [x] Do logical separation on open api spec level if possible, Or create separate schemas  and use in implementation.
- [ ] Add schema for query result, instead of `result: "string"`
- [x] Separate Worksheet payloads for update, create
- [x] Fix deploy error

### CODE REVIEW

File: crates/runtime/src/http/ui/volumes/models.rs [hunk 1]
```diff
@@ -15,26 +15,99 @@
...
 
-use icebucket_metastore::models::IceBucketVolume;
+use icebucket_metastore::models::{
+    AwsCredentials, IceBucketFileVolume, IceBucketS3Volume, IceBucketVolume, IceBucketVolumeType,
+};
 use serde::{Deserialize, Serialize};
 use utoipa::ToSchema;
 
+#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, Eq, PartialEq)]
+pub struct S3Volume {
```
Comment (DanCodedThis) [inline crates/runtime/src/http/ui/volumes/models.rs:25]: Why do you redefine everything, if you can just `type S3Volume = IcebucketS3Volume`? This goes for any type with the prefix. And the new type will retain everything from the old type but the name.

Comment (DanCodedThis) [reply crates/runtime/src/http/ui/volumes/models.rs:25]: Does type redefinition resolve in the wrong schema for **_OpenAPI_**?

Comment (YaroslavLitvinov) [reply crates/runtime/src/http/ui/volumes/models.rs:25]: > Why do you redefine everything, if you can just `type S3Volume = IcebucketS3Volume`? This goes for any type with the prefix.

It's not about renaming it in code. The goal is to change a type name in the generated open api spec at ui_openapi.json.  Approach you suggest just has no effect on spec.

File: crates/history/src/entities/worksheet.rs [hunk 2]
```diff
@@ -43,25 +41,25 @@ impl Worksheet {
...
             id,
-            name: None,
+            name,
             content,
             created_at,
             updated_at: created_at,
         }
     }
 
     pub fn set_name(&mut self, name: String) {
```
Comment (DanCodedThis) [inline crates/history/src/entities/worksheet.rs:57]: Nitpick: why do we need `fn set_name` if the name is `pub`? (same goes for `fn set_content`)

**Review by DanCodedThis — APPROVED** [review]
Overall, let's merge

File: crates/history/src/entities/worksheet.rs (hunk 2 above)
Comment (YaroslavLitvinov) [reply crates/history/src/entities/worksheet.rs:57]: > Nitpick: why do we need `fn set_name` if the name is `pub`? (same goes for `fn set_content`)

this interface was not created  to be reusable for public, and not refined yet. Doing mutations over interface always takes over direct mutations of values even if they are public.

File: Cargo.toml [hunk 3]
```diff
@@ -60,6 +60,9 @@ datafusion-macros = { git = "https://github.com/Embucket/datafusion.git", rev =
 
 # issue #309
 chrono = { git = "https://github.com/chronotope/chrono.git", rev = "8b863490d88ba098038392c8aa930012ffd0c439" }
+# https://github.com/juhaku/utoipa/issues/1345
```
Comment (rampage644) [inline Cargo.toml]: This is already merged in main, perhaps by the time we ready to merge this PR we can just bump the version

File: crates/history/src/entities/worksheet.rs (hunk 2 above)
Comment (rampage644) [reply crates/history/src/entities/worksheet.rs:57]: Can you elaborate? I also don't get it. Why not `with_name` idiomatic approach?

File: crates/runtime/src/http/ui/schemas/models.rs [hunk 4]
```diff
@@ -15,26 +15,56 @@
...
+impl From<IceBucketSchema> for Schema {
+    fn from(schema: IceBucketSchema) -> Self {
+        Self {
+            schema: schema.ident.schema,
+            database: schema.ident.database,
+        }
+    }
+}
+
+// TODO: Remove it when found why it can't locate .into() if only From trait implemeted
```
Comment (rampage644) [inline crates/runtime/src/http/ui/schemas/models.rs:38]: Perhaps it cannot locate it since you have to implement `impl From<Schema> for IceBucketSchema` in another crate

**Review by rampage644 — APPROVED** [review]

File: crates/runtime/src/http/ui/schemas/models.rs (hunk 4 above)
Comment (YaroslavLitvinov) [reply crates/runtime/src/http/ui/schemas/models.rs:38]: > Can you elaborate? I also don't get it. Why not with_name idiomatic approach?
What is the question? I didn't get it.

> Perhaps it cannot locate it since you have to implement impl From<Schema> for IceBucketSchema in another crate
probably, but ToInto implementations were added for the same class

File: crates/history/src/entities/worksheet.rs (hunk 2 above)
Comment (YaroslavLitvinov) [reply crates/history/src/entities/worksheet.rs:57]: I don't get the question.
