### PR TITLE
`to_time`, `try_to_time` scalar functions

### LINKED ISSUE #623: [BUG] Missing function: to_time
**Function:** `to_time`
**Category:** Conversion
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/to_time

**Test SQL:**
```sql
SELECT TO_TIME('14:30:00');
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT TO_TIME('14:30:00');
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'to_time'.                                                                           │
│ Did you mean 'to_date'?                                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #565

### PR DESCRIPTION
**Pull request by ravlio**
Closes #623

### CODE REVIEW

File: crates/runtime/src/execution/datafusion/functions/to_time.rs [hunk 1]
```diff
@@ -0,0 +1,380 @@
...
+    fn aliases(&self) -> &[String] {
+        &self.aliases
+    }
+
+    fn signature(&self) -> &Signature {
+        &self.signature
+    }
+
+    fn return_type(&self, _arg_types: &[DataType]) -> DFResult<DataType> {
+        Ok(DataType::Time64(TimeUnit::Nanosecond))
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: I think `Microseconds` more appropriate since DF likes them, and I think we use them in our codebase also in UDFs particularly, maybe something changed?

Comment (DanCodedThis) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: or Snowflake/dbt not DF

File: crates/runtime/src/execution/datafusion/functions/to_time.rs [hunk 2]
```diff
@@ -0,0 +1,380 @@
...
+            }
+            DataType::Timestamp(
+                TimeUnit::Second
+                | TimeUnit::Millisecond
+                | TimeUnit::Microsecond
+                | TimeUnit::Nanosecond,
+                _,
+            ) => {
+                let arr = cast(arr, &DataType::Timestamp(TimeUnit::Nanosecond, None))?;
+                let arr = arr
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/to_time.rs:249]: Why the double cast?

**Review by DanCodedThis — APPROVED** [review]
Otherwise LGTM

File: crates/runtime/src/execution/datafusion/functions/to_time.rs [hunk 3]
```diff
@@ -0,0 +1,380 @@
+use arrow::compute::cast;
```
Comment (rampage644) [inline crates/runtime/src/execution/datafusion/functions/to_time.rs]: From now on, let's please use `datafusion::` dependencies instead of arrow.
`use arrow::compute::cast` -> `use datafusion:arrow:compute::cast` and `use arrow_array` -> `use datafusion::arrow::array`

File: crates/runtime/src/execution/datafusion/functions/to_time.rs (hunk 1 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: @rampage644 what do you think?

File: crates/runtime/src/execution/datafusion/functions/to_time.rs [hunk 4]
```diff
@@ -0,0 +1,380 @@
...
+// AM , PM - Ante meridiem (AM) / post meridiem (PM). Use this only with HH12 (not with HH24).
+// MI - Two digits for minute (00 through 59).
+// SS - Two digits for second (00 through 59).
+// FF[0-9] - Fractional seconds with precision 0 (seconds) to 9 (nanoseconds), e.g. FF, FF0, FF3, FF9. Specifying FF is equivalent to FF9 (nanoseconds).
+// Example: TO_TIME('11.15.00', 'HH24.MI.SS')
+#[derive(Debug)]
+pub struct ToTimeFunc {
+    signature: Signature,
+    aliases: Vec<String>,
+    try_: bool,
```
Comment (rampage644) [inline crates/runtime/src/execution/datafusion/functions/to_time.rs]: r#try?

Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs]: or `is_try`. Let's make it `r#try` then.

Comment (rampage644) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs]: `is_try` also good

File: crates/runtime/src/execution/datafusion/functions/to_time.rs (hunk 1 above)
Comment (rampage644) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: For the context, we used Microseconds in timestamps since there is no support for nanoseconds accuracy in Iceberg and we have to coerce to microseconds.

I am not sure though if this warrants "always avoid nanoseconds" approach everywhere. One day the Iceberg spec will support nanoseconds and then we'll have to update that. 

@DanCodedThis can you elaborate on "datafusion doesn't like nanoseconds"?

Comment (rampage644) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: I would support as much as possible in UDFs, and if there are problems with timestamp accuracy, we better of deal with this somewhere else, in a single place (code flow).

Comment (DanCodedThis) [reply crates/runtime/src/execution/datafusion/functions/to_time.rs:107]: > For the context, we used Microseconds in timestamps since there is no support for nanoseconds accuracy in Iceberg and we have to coerce to microseconds.
> 
> I am not sure though if this warrants "always avoid nanoseconds" approach everywhere. One day the Iceberg spec will support nanoseconds and then we'll have to update that.
> 
> @DanCodedThis can you elaborate on "datafusion doesn't like nanoseconds"?

I think I remember now, you explained exactly what I wanted to convey, it was the Iceberg format. Sorry for the misinfo

**Review by rampage644 — APPROVED** [review]
