### PR TITLE
Set variable, set entity within session

### LINKED ISSUE #173: Support setting variables with SET statement
Add support for setting variables using SET, like `SET timezone='UTC'` query.

More context:
Since issue https://github.com/Embucket/control-plane-v2/issues/157 been resolved, and `warehouse_id` argument is not anymore provided in `query` functions and handlers, it failing with error "Warehouse name not found". As no FQN present in query and warehouse name can't be interred.

### PR DESCRIPTION
**Pull request by osipovartem**
Closes #173 and #175

### CODE REVIEW

**Review by DanCodedThis — APPROVED** [review]

**Review by rampage644 — APPROVED** [review]

File: crates/runtime/src/datafusion/execution.rs [hunk 1]
```diff
@@ -89,8 +89,56 @@ impl SqlExecutor {
         // etc
         if let DFStatement::Statement(s) = statement {
             match *s {
-                Statement::AlterSession { .. } => {
-                    return Box::pin(self.alter_session_query(*s)).await;
+                Statement::AlterSession {
+                    set,
+                    session_params,
+                } => {
+                    let params = session_params
```
Comment (eadgbear) [inline crates/runtime/src/datafusion/execution.rs:96]: The `session_params` are owned why are we cloning them? `into_iter` should give us an owned HashMap
