### PR TITLE
`iff` scalar function

### LINKED ISSUE #586: [BUG] Snowflake Function: iff
**Function:** `iff`
**Category:** Conditional expression
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/iff

**Test SQL:**
```sql
SELECT IFF(1 < 2, 'Condition True', 'Condition False');
```

**Expected Result:**
```
Condition True
```

**Actual Result:**
```
SELECT IFF(1 < 2, 'Condition True', 'Condition False');
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'iff'.                                                                               │
│ Did you mean 'left'?                                                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #564

### PR DESCRIPTION
**Pull request by ravlio**
Closes #586

### CODE REVIEW

File: crates/runtime/src/execution/datafusion/functions/iff.rs [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+
+        Ok(ColumnarValue::Array(arr))
+    }
+}
+
+fn return_type(lhs: &DataType, rhs: &DataType) -> DataType {
+    match (lhs, rhs) {
+        (&DataType::Null, _) => rhs.clone(),
+        (_, &DataType::Null) => lhs.clone(),
+        _ => rhs.clone(),
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/iff.rs:107]: Does this branch ever trigger?

File: crates/runtime/src/execution/datafusion/functions/iff.rs [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+        let mut res = Vec::with_capacity(input.len());
+        for v in &input {
+            if let Some(v) = v {
+                if v {
+                    res.push(lhs.clone());
+                } else {
+                    res.push(rhs.clone());
+                }
+            } else {
+                res.push(rhs.clone());
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/iff.rs:93]: What are the conditions to trigger this else?

File: crates/runtime/src/execution/datafusion/functions/mod.rs [hunk 3]
```diff
@@ -93,6 +95,13 @@ macro_rules! numeric_to_boolean {
 #[allow(clippy::cognitive_complexity, clippy::unwrap_used)]
 pub(crate) fn array_to_boolean(arr: &ArrayRef) -> Result<BooleanArray> {
     Ok(match arr.data_type() {
+        DataType::Null => {
+            let mut boolean_array = BooleanArray::builder(arr.len());
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/mod.rs]: Nitpick: There may be an associated function or a method that allows to build a null array of length.

**Review by DanCodedThis — APPROVED** [review]
Overall LGTM

File: crates/runtime/src/execution/datafusion/functions/iff.rs (hunk 1 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/iff.rs:107]: sure. For instance, `SELECT IFF(NULL, 'true', 'false')` will give you `DataType::Utf8`

File: crates/runtime/src/execution/datafusion/functions/iff.rs (hunk 2 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/iff.rs:93]: `SELECT IFF(NULL, 'true', 'false')` The input is null in this case thus this branch will be triggered, According to the rules

File: crates/runtime/src/execution/datafusion/functions/mod.rs (hunk 3 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/mod.rs]: yes, changed it to `BooleanArray::new_null(arr.len())` thanks
