### PR TITLE
UI Utoipa schema fix

### LINKED ISSUE #440: api: UI Tables schema fixes
- Fix schema path for `getTables`
- Rename `TableColumsInfoResponse` -> `TableColumnsResponse`
- `TableColumnInfo` -> `TableColumn`

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #440

- [x] Fix schema path for `getTables`
- [x] Fixes in OAS related to queries, affected tests updates
- [x] Rename `TableColumsInfoResponse` -> `TableColumnsResponse` & `TableColumnInfo` -> `TableColumn`

### CODE REVIEW

File: crates/runtime/src/http/ui/tables/handlers.rs [hunk 1]
```diff
@@ -368,7 +367,7 @@ pub async fn upload_file(
 
 #[utoipa::path(
     get,
-    path = "/ui/databases/{databaseName}/schemas/{schemaName}/tables",
+    path = "/ui/databases/{databaseName}/schemas/tables/{schemaName}/tables",
```
Comment (YaroslavLitvinov) [inline crates/runtime/src/http/ui/tables/handlers.rs]: bad path: "/ui/databases/{databaseName}/schemas/tables/{schemaName}/tables",

**Review by YaroslavLitvinov — DISMISSED** [review]

File: crates/runtime/src/http/ui/tables/handlers.rs (hunk 1 above)
Comment (DanCodedThis) [reply crates/runtime/src/http/ui/tables/handlers.rs]: good catch

**Review by rampage644 — APPROVED** [review]
