### PR TITLE
`previous_day` scalar function

### LINKED ISSUE #613: [BUG] Missing function: previous_day
**Function:** `previous_day`
**Category:** Date & time
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/previous_day

**Test SQL:**
```sql
SELECT PREVIOUS_DAY('2025-05-01'::date, 'SUN');
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT PREVIOUS_DAY('2025-05-01'::date, 'SUN');
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'previous_day'.                                                                      │
│ Did you mean 'today'?                                                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #515

### PR DESCRIPTION
**Pull request by ravlio**
closes #613

### CODE REVIEW

File: crates/embucket-functions/src/datetime/previous_day.rs [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+}
+
+#[allow(
+    clippy::unwrap_used,
+    clippy::as_conversions,
+    clippy::cast_possible_truncation,
+    clippy::cast_lossless
+)]
+fn prev_day(ndt: &NaiveDateTime, dow: &str) -> DFResult<NaiveDateTime> {
+    let target_dow = if dow.starts_with("su") {
```
Comment (osipovartem) [inline crates/embucket-functions/src/datetime/previous_day.rs]: maybe match will be better here

**Review by Vedin — APPROVED** [review]

File: crates/embucket-functions/src/datetime/previous_day.rs (hunk 1 above)
Comment (ravlio) [reply crates/embucket-functions/src/datetime/previous_day.rs]: right

**Review by Vedin — APPROVED** [review]
