### PR TITLE
UI Decouple Tables Handlers (Info & Columns) + TableDataPreview "fix"

### LINKED ISSUE #406: api: UI Decouple Tables Get Table Info & Get Table Columns
- `/database/${databaseName}/schemas/${schemaName}/tables/${tableName}/info` GET (No columns info)
- `/database/${databaseName}/schemas/${schemaName}/tables/${tableName}/columns` GET (Just columns info)

### LINKED ISSUE #411: TableMetadata doesn't contain anything in Summary Hashmap after `INSERT INTO`
- `TableMetadata` from _**iceberg_spec**_ (JanKaul) has a `Summary` on each `Snapshot`. 
- `Summary` is an `Operation` and a `other: HashMap<String, String>` which should hold under certain keys certain values, like in the code below. 
- After inserting 35 rows into a table, (**_crates/runtime/src/http/ui/tests/tables.rs_** test in **_DanCodedThis/406-ui-decouple-tables-handlers_** branch) it has no records inside the `HashMap` at all, nothing.

P.S. Point of reference for me was our old impl for `Statistics` (before **_Metastore_**): https://github.com/Embucket/icebucket/blob/21265cb71701c65d0d20e749bccda9edc271eb0c/crates/nexus/src/http/ui/models/table.rs#L261

Code of the handler (copied without utopia spec and tracing):
```Rust
pub async fn get_table_info(
    State(state): State<AppState>,
    Path((database_name, schema_name, table_name)): Path<(String, String, String)>,
) -> TablesResult<Json<TableInfoResponse>> {
    let ident = IceBucketTableIdent::new(&database_name, &schema_name, &table_name);
    match state.metastore.get_table(&ident).await {
        Ok(Some(rw_object)) => {
            let mut total_bytes = 0;
            let mut total_rows = 0;
            if let Ok(Some(latest_snapshot)) = rw_object.metadata.current_snapshot(None) {
                dbg!("latest snapshot");
                dbg!(&latest_snapshot.summary().other);
                total_bytes = latest_snapshot
                    .summary()
                    .other
                    .get("total-files-size")
                    .and_then(|value| {dbg!("total-files-size"); value.parse::<i64>().ok()})
                    .unwrap_or(0);
                total_rows = latest_snapshot
                    .summary()
                    .other
                    .get("total-records")
                    .and_then(|value| {dbg!("total-records"); value.parse::<i64>().ok()})
                    .unwrap_or(0);
            }
            Ok(Json(
                TableInfoResponse {
                    data: TableInfo {
                        name: rw_object.ident.table.clone(),
                        total_rows,
                        total_bytes,
                        created_at: rw_object.created_at,
                        updated_at: rw_object.updated_at,
                    }
                }
            ))
        },
        Ok(None) => Err(TablesAPIError::GetMetastore {
            source: MetastoreError::TableNotFound {
                table: database_name,
                schema: schema_name,
                db: table_name,
            },
        }),
        Err(e) => Err(TablesAPIError::GetMetastore { source: e }),
    }
}
```

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #406, #407, #408 & bug in #410 

- `/ui/../tables/${tableName}/statistics` (renamed from `info`) now doesn't return columns. Only returns the table metadata info. 
- `/ui/../tables/${tableName}/columns` returns just columns info.
- `/ui/../tables/${tableName}/preview` only calls the sql once using the metadata names to do the casting instead of getting them from `information_schema.columns` as before.

### CODE REVIEW

File: crates/runtime/src/http/ui/tables/handlers.rs [hunk 1]
```diff
@@ -55,126 +59,120 @@ use utoipa::OpenApi;
...
-    });
-    Ok(Json(TableInfoResponse {
-        data: TableInfo {
-            name: table_name,
-            columns,
-            total_rows,
-        },
-    }))
+        .map_err(|e| TablesAPIError::GetExecution { source: e })?;
+    let mut items: Vec<TableColumnInfo> = vec![];
```
Comment (rampage644) [inline crates/runtime/src/http/ui/tables/handlers.rs]: Can this be refactored with `column_infos.map_err(...).map(TableColumnInfo::into).collect()` or smth similiar?

File: crates/runtime/src/http/ui/tables/handlers.rs [hunk 2]
```diff
@@ -205,26 +203,26 @@ pub async fn get_table_preview_data(
...
-            .column(0)
-            .as_any()
-            .downcast_ref::<StringArray>()
-            .unwrap();
-        for column_name in column_name_array {
-            column_names.push(column_name.unwrap().to_string());
+    let ident = IceBucketTableIdent::new(&database_name, &schema_name, &table_name);
+    let column_names = match state.metastore.get_table(&ident).await {
+        Ok(Some(rw_object)) => {
+            let mut items: Vec<String> = vec![];
```
Comment (rampage644) [inline crates/runtime/src/http/ui/tables/handlers.rs]: same: possible to replace with iterator?

**Review by rampage644 — APPROVED** [review]
minor comments
