### PR TITLE
engine: `regexp_instr`

### LINKED ISSUE #638: engine: Missing function `regexp_instr`
**Function:** `regexp_instr`
**Category:** Regular expressions
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/regexp_instr

**Test SQL:**
```sql
SELECT REGEXP_INSTR('snowflake', 'flake');
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT REGEXP_INSTR('snowflake', 'flake');
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'regexp_instr'.                       │
│ Did you mean 'regexp_substr'?                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #574

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #638

- [x] `regexp_instr` impl (return type is `Int64` for better compatibility with our code)
- [x] Uses an iterator approach for performance and reusability, which opens a path to implement other regexp functions with ease
- [x] Docs
- [x] Extensible insta tests (surprised even me that some of them work out of the box)
- [x] SLT tests

Reference: https://docs.snowflake.com/en/sql-reference/functions/regexp_instr

### CODE REVIEW

**Comment by DanCodedThis** [comment]
I tested the fixed slts locally, they run with no errors on `regexp_instr` finally:
- removed redundanut `regexp_substr` from `regexp_instr`
- fixed columns
- fixed tabs vs 4 spaces idents bug in this slts

File: crates/embucket-functions/src/regexp/regexp_instr.rs [hunk 1]
```diff
@@ -0,0 +1,348 @@
...
+                        Coercion::new_exact(TypeSignatureClass::Integer),
+                    ]),
+                ],
+                Volatility::Immutable,
+            ),
+        }
+    }
+    #[allow(clippy::too_many_lines, clippy::unwrap_used)]
+    fn take_args_values(args: &[ColumnarValue]) -> DFResult<(usize, usize, usize, &str, usize)> {
+        let position = args.get(2).map_or_else(
```
Comment (osipovartem) [inline crates/embucket-functions/src/regexp/regexp_instr.rs:123]: looks like a pattern for macro rule

Comment (DanCodedThis) [reply crates/embucket-functions/src/regexp/regexp_instr.rs:123]: Also thought of that, but there are subtle changes between them, even between the same ones types. Not sure if it's worth the effort.

**Review by rampage644 — APPROVED** [review]
