### PR TITLE
Session: Add current session context rewriter with basic UDFs

### LINKED ISSUE #595: [BUG] Snowflake Function: current_database
**Function:** `current_database`
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_database

**Test SQL:**
```sql
SELECT CURRENT_DATABASE();
```

**Expected Result:**
```
Name of the current database (string)
```

**Actual Result:**
```
SELECT CURRENT_DATABASE();
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_database'.                                                                  │
│ Did you mean 'current_date'?                                                                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### LINKED ISSUE #665: [BUG] Missing function: current_warehouse
**Function:** `current_warehouse`
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_warehouse

**Test SQL:**
```sql
SELECT CURRENT_WAREHOUSE();
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT CURRENT_WAREHOUSE();
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_warehouse'.                  │
│ Did you mean 'current_date'?                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### LINKED ISSUE #667: [BUG] Missing function: current_schema
**Function:** `current_schema`
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_schema

**Test SQL:**
```sql
SELECT CURRENT_SCHEMA();
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT CURRENT_SCHEMA();
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_schema'.                     │
│ Did you mean 'current_time'?                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### PR DESCRIPTION
**Pull request by osipovartem**
- added basic stub for current_database, current_schema, current_warehouse
- added logical plan rewriter to take into account current query context
NOTE 
- ❗**we cannot use** UDFs directly since it is not possible to share ctx 
- ❗**we cannot use** OptimizationRule since we have to register in before query execution during session creation
- **we can** use AST visitor to transform statement with literals, but this is not good way since sql syntax for current_database, current_schema, current_warehouse, etc. still will be missing.
Closes #595
Closes #667
Closes #665

### CODE REVIEW

File: crates/core-executor/src/datafusion/rewriters/session_context.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    fn rewrite_expr(&self, expr: Expr) -> Expr {
+        match expr {
+            Expr::ScalarFunction(fun) if fun.name().to_lowercase() == "current_database" => {
+                Expr::Literal(self.database.clone().into()).alias(fun.name())
+            }
+            Expr::ScalarFunction(fun) if fun.name().to_lowercase() == "current_schema" => {
+                Expr::Literal(self.schema.clone().into()).alias(fun.name())
+            }
+            Expr::ScalarFunction(fun) if fun.name().to_lowercase() == "current_warehouse" => {
+                Expr::Literal(self.warehouse.clone().into()).alias(fun.name())
```
Comment (Vedin) [inline crates/core-executor/src/datafusion/rewriters/session_context.rs:30]: I'm a little bit afraid of what'll happen on query like `select current_warehouse() as cr`. I believe it should work out of the box and return a result as `cr` but did you test something like this?

**Review by Vedin — APPROVED** [review]
lgtm! Please just check the behaviour I mentioned in the comment above.

File: crates/core-executor/src/datafusion/rewriters/session_context.rs (hunk 1 above)
Comment (osipovartem) [reply crates/core-executor/src/datafusion/rewriters/session_context.rs:30]: Maybe better to remove default aliases. It's a bug, good catch

Comment (osipovartem) [reply crates/core-executor/src/datafusion/rewriters/session_context.rs:30]: Added tests + extended logic for aliases

**Review by Vedin — APPROVED** [review]
