### PR TITLE
engine: `dbt-gitlab` seed csv string to int32 cast fix

### LINKED ISSUE #1639: engine: `dbt-gitlab` seed csv string to int32 cast error
```
15:47:43    Database Error in seed tableau_cloud_site_content (seeds/tableau_cloud/tableau_cloud_site_content.csv)
  010001 (02000): Arrow error: Cast error: Cannot cast string '50.0' to value of Int32 type
```

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #1639

- [x] Int32 & Int64 casts from Utf8 are cast `to_decimal` before to be able to cast values like `'50.0'` (this is supported by Snowflake, but not by DataFusion)
- [x] Integer & Int now -> Int64, instead of Int32 for better compatibility
- [x] Insta tests
- [x] dbt-gitlab tested

P.S. Should later be changed to cast `to_double`, for performance reasons (this udf is not implemented yet)

### CODE REVIEW

**Comment by DanCodedThis** [comment]
New error:
```
14:24:10    Database Error in seed tableau_cloud_site_content (seeds/tableau_cloud/tableau_cloud_site_content.csv)
  010001 (02000): Arrow error: Cast error: value of 1073741824000 is out of range Int32
```

Int32 is an incorrect type, we should choose a bigger, I think. For Snowflake, they use Number.

**Comment by DanCodedThis** [comment]
> New error:
> 
> ```
> 14:24:10    Database Error in seed tableau_cloud_site_content (seeds/tableau_cloud/tableau_cloud_site_content.csv)
>   010001 (02000): Arrow error: Cast error: value of 1073741824000 is out of range Int32
> ```
> 
> Int32 is an incorrect type, we should choose a bigger, I think. For Snowflake, they use Number.

For now, maybe we could just use Int64 everywhere?

**Comment by DanCodedThis** [comment]
> > New error:
> > ```
> > 14:24:10    Database Error in seed tableau_cloud_site_content (seeds/tableau_cloud/tableau_cloud_site_content.csv)
> >   010001 (02000): Arrow error: Cast error: value of 1073741824000 is out of range Int32
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Int32 is an incorrect type, we should choose a bigger, I think. For Snowflake, they use Number.
> 
> For now, maybe we could just use Int64 everywhere?

Fixed.

File: crates/core-executor/src/datafusion/logical_analyzer/cast_analyzer.rs [hunk 1]
```diff
@@ -96,10 +104,46 @@ impl CastAnalyzer {
...
+    fn rewrite_integer_cast(
+        expr: &Expr,
+        data_type: DataType,
+        try_mode: bool,
+    ) -> DFResult<Transformed<Expr>> {
+        let new_expr = if try_mode {
+            let internal = Expr::ScalarFunction(ScalarFunction {
+                func: Arc::new(ScalarUDF::from(ToDecimalFunc::new(try_mode))),
+                args: vec![expr.clone()],
+            });
```
Comment (osipovartem) [inline crates/core-executor/src/datafusion/logical_analyzer/cast_analyzer.rs]: move Expr::ScalarFunction out from if (same code)

File: crates/core-executor/src/datafusion/logical_analyzer/cast_analyzer.rs [hunk 2]
```diff
@@ -96,10 +104,46 @@ impl CastAnalyzer {
                     args: vec![expr.clone()],
                 })))
             }
+            data_type @ (DataType::Int32 | DataType::Int64) => {
```
Comment (osipovartem) [inline crates/core-executor/src/datafusion/logical_analyzer/cast_analyzer.rs]:
```rust
            DataType::Int32 | DataType::Int64
                if matches!(expr.get_type(schema), Ok(DataType::Utf8)) =>
            {
                Self::rewrite_integer_cast(expr, data_type.clone(), try_mode)
            }
```

**Review by osipovartem — APPROVED** [review]

**Review by osipovartem — APPROVED** [review]
