### PR TITLE
`to_boolean` and `try_to_boolean` function

### LINKED ISSUE #602: [BUG] Snowflake Function: to_boolean
**Function:** `to_boolean`
**Category:** Conversion
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/to_boolean

**Test SQL:**
```sql
SELECT TO_BOOLEAN('False');
```

**Expected Result:**
```
FALSE
```

**Actual Result:**
```
SELECT TO_BOOLEAN('False');
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'to_boolean'.                                                                        │
│ Did you mean 'bool_and'?                                                                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #565

### PR DESCRIPTION
**Pull request by ravlio**
Closes #602

### CODE REVIEW

File: crates/runtime/src/execution/datafusion/functions/to_boolean.rs [hunk 1]
```diff
@@ -0,0 +1,242 @@
...
+        let arr = match args[0].clone() {
+            ColumnarValue::Array(arr) => arr,
+            ColumnarValue::Scalar(v) => v.to_array()?,
+        };
+
+        let arr = match arr.data_type() {
+            DataType::Utf8 => {
+                let arr = as_string_array(&arr);
+                let mut res = BooleanBuilder::with_capacity(arr.len());
+                let true_ = ["true", "t", "yes", "y", "on", "1"];
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/to_boolean.rs]: It probably can be `const` and any type of `set`

File: crates/runtime/src/execution/datafusion/functions/to_boolean.rs [hunk 2]
```diff
@@ -0,0 +1,242 @@
...
+    fn signature(&self) -> &Signature {
+        &self.signature
+    }
+
+    fn return_type(&self, _arg_types: &[DataType]) -> DFResult<DataType> {
+        Ok(DataType::Boolean)
+    }
+
+    fn invoke_with_args(&self, args: ScalarFunctionArgs) -> DFResult<ColumnarValue> {
+        assert_eq!(args.args.len(), 1);
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/to_boolean.rs]: Is this expected to panic?

**Review by DanCodedThis — APPROVED** [review]
Otherwise LGTM

File: crates/runtime/src/execution/datafusion/functions/mod.rs [hunk 3]
```diff
@@ -59,3 +68,36 @@ mod macros {
...
+
+pub(crate) fn array_to_boolean(arr: &ArrayRef) -> Result<BooleanArray> {
+    let arr = arr.as_ref();
+    let mut boolean_array = BooleanArray::builder(arr.len());
+    for i in 0..arr.len() {
+        if arr.is_null(i) {
+            boolean_array.append_null();
+        } else {
+            let b = match arr.data_type() {
+                DataType::Boolean => downcast_value!(arr, BooleanArray).value(i),
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/datafusion/functions/mod.rs]: Why are we downcasting the whole array multiple times (per element)?

File: crates/runtime/src/execution/datafusion/functions/to_boolean.rs (hunk 2 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/to_boolean.rs]: it is, but signature should not pass arguments of the wrong types, it is additional check. I took this assert from other DF functions. I'll remove it though

File: crates/runtime/src/execution/datafusion/functions/to_boolean.rs (hunk 1 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/to_boolean.rs]: nice catch

File: crates/runtime/src/execution/datafusion/functions/mod.rs (hunk 3 above)
Comment (ravlio) [reply crates/runtime/src/execution/datafusion/functions/mod.rs]: idk to be honest how could I do this :) Thanks for finding the bottleneck, will rewrite

File: crates/runtime/src/execution/datafusion/functions/to_boolean.rs (hunk 2 above)
Comment (DanCodedThis) [reply crates/runtime/src/execution/datafusion/functions/to_boolean.rs]: > it is, but signature should not pass arguments of the wrong types, it is additional check. I took this assert from other DF functions. I'll remove it though

However, my experience with DF signature, is it sometimes doesn't work :) (`convert_timezone`) However it was with similar signature types, but different argument number length. Anyway, here it shouldn't be a problem I guess

**Comment by ravlio** [comment]
@DanCodedThis kindly ask you to re-check. I made a batch processing macro `numeric_to_boolean`

**Comment by DanCodedThis** [comment]
BTW, about `set`, `phf` or `lazy_static` maybe good here for true compile time sets, but probably overkill

**Review by DanCodedThis — APPROVED** [review]
LGTM
