### PR TITLE
engine: `Like` type coercion fix

### LINKED ISSUE #1679: engine: `LIKE` type_coersion error
## dbt-gitlab

```
[0m14:35:01    Database Error in model sfdc_campaign_source (models/sources/sfdc/sfdc_campaign_source.sql)
  010001 (02000): type_coercion
  caused by
  Error during planning: There isn't a common type to coerce Int32 and Utf8 in LIKE expression
  compiled code at target/run/gitlab_snowflake/models/sources/sfdc/sfdc_campaign_source.sql
[0m14:35:01  
[0m14:35:01    Database Error in model sfdc_bizible_touchpoint_source (models/sources/sfdc/sfdc_bizible_touchpoint_source.sql)
  010001 (02000): type_coercion
  caused by
  Error during planning: There isn't a common type to coerce Int32 and Utf8 in LIKE expression
  compiled code at target/run/gitlab_snowflake/models/sources/sfdc/sfdc_bizible_touchpoint_source.sql
```

## Investigation

The csv file and the table both contain for the compared column an **Int32** value.

## Example (MRE)

- Snowflake:
```sql
SELECT column1 FROM VALUES (910), (256) WHERE '%http' LIKE column1;
```
->
**No result** (correct)

- Embucket:
```sql
SELECT column1 FROM VALUES (910), (256) WHERE '%http' LIKE column1;
```
->
**Error**

## Solution

**Snowflake** casts both subject and the pattern with `to_char` if it's not a string.

**Embucket** doesn't, so we need to, if we get `LIKE` to add a udf call to `to_char` conversion.

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #1679

- [x] Added a logical analyzer rule checking the type of the **subject** & **pattern** in the `Like` expr
- [x] Restructured the rule ordering, since default analyzer base rules fail on logical analysis if the newly added rule is not called before them
- [x] Other rules are ordered as before after the base default rules (no breaking changes)
- [x] Added insta tests
- [x] dbt-gitlab tested

### CODE REVIEW

**Comment by DanCodedThis** [comment]
P.S. After fix, we reduced our type_coersion errors in half (was 8 now 4), but it added additionally 8 new errors (from passed I assume) which appears to fail on the rule. But actually, if you take a look, they fail because of schema name mismatch. For exmaple:
```
[0m18:06:11    Database Error in model prep_crm_opportunity_calcs (models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql)
  010001 (02000): LikeILikeTypeAnalyzer
  caused by
  Schema error: No field named updated_source_with_net_arr_logic.sales_segmentation_employees. Valid fields are updated_source_with_net_arr_logic.opportunity_name, updated_source_with_net_arr_logic.is_closed, updated_source_with_net_arr_logic.valid_deal_count, updated_source_with_net_arr_logic.deployment_preference, updated_source_with_net_arr_logic.generated_source, updated_source_with_net_arr_logic.lead_source, updated_source_with_net_arr_logic.merged_opportunity_id, updated_source_with_net_arr_logic.duplicate_opportunity_id, updated_source_with_net_arr_logic.contract_reset_opportunity_id, updated_source_with_net_arr_logic.account_owner, updated_source_with_net_arr_logic.opportunity_owner, updated_source_with_net_arr_logic.opportunity_owner_manager, updated_source_with_net_arr_logic.opportunity_owner_department, updated_source_with_net_arr_logic.crm_sales_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id_lookup, updated_source_with_net_arr_logic.opportunity_development_representative, updated_source_with_net_arr_logic.sales_path, updated_source_with_net_arr_logic.sales_qualified_date, updated_source_with_net_arr_logic.iqm_submitted_by_role, updated_source_with_net_arr_logic.subscription_type, updated_source_with_net_arr_logic.stage_name, updated_source_with_net_arr_logic.acv, updated_source_with_net_arr_logic.amount, updated_source_with_net_arr_logic.competitors, updated_source_with_net_arr_logic.critical_deal_flag, updated_source_with_net_arr_logic.forecast_category_name, updated_source_with_net_arr_logic.forecasted_iacv, updated_source_with_net_arr_logic.iacv_created_date, updated_source_with_net_arr_logic.incremental_acv, updated_source_with_net_arr_logic.invoice_number, updated_source_with_net_arr_logic.is_refund, updated_source_with_net_arr_logic.is_downgrade, updated_source_with_net_arr_logic.is_swing_deal, updated_source_with_net_arr_logic.is_edu_oss, updated_source_with_net_arr_logic.is_ps_opp, updated_source_with_net_arr_logic.net_incremental_acv, updated_source_with_net_arr_logic.primary_campaign_source_id, updated_source_with_net_arr_logic.probability, updated_source_with_net_arr_logic.professional_services_value, updated_source_with_net_arr_logic.edu_services_value, updated_source_with_net_arr_logic.investment_services_value, updated_source_with_net_arr_logic.pushed_count, updated_source_with_net_arr_logic.reason_for_loss, updated_source_with_net_arr_logic.reason_for_loss_details, updated_source_with_net_arr_logic.refund_iacv, updated_source_with_net_arr_logic.downgrade_iacv, updated_source_with_net_arr_logic.renewal_acv, updated_source_with_net_arr_logic.renewal_amount, updated_source_with_net_arr_logic.sdr_pipeline_contribution, updated_source_with_net_arr_logic.solutions_to_be_replaced, updated_source_with_net_arr_logic.technical_evaluation_date, updated_source_with_net_arr_logic.total_contract_value, updated_source_with_net_arr_logic.recurring_amount, updated_source_with_net_arr_logic.true_up_amount, updated_source_with_net_arr_logic.proserv_amount, updated_source_with_net_arr_logic.other_non_recurring_amount, updated_source_with_net_arr_logic.upside_swing_deal_iacv, updated_source_with_net_arr_logic.is_web_portal_purchase, updated_source_with_net_arr_logic.partner_initiated_opportunity, updated_source_with_net_arr_logic.user_segment, updated_source_with_net_arr_logic.subscription_start_date, updated_source_with_net_arr_logic.subscription_end_date, updated_source_with_net_arr_logic.subscription_renewal_date, updated_source_with_net_arr_logic.true_up_value, updated_source_with_net_arr_logic.order_type_current, updated_source_with_net_arr_logic.arr_basis, updated_source_with_net_arr_logic.arr, updated_source_with_net_arr_logic.xdr_net_arr_stage_3, updated_source_with_net_arr_logic.xdr_net_arr_stage_1, updated_source_with_net_arr_logic.net_arr_stage_1, updated_source_with_net_arr_logic.enterprise_agile_planning_net_arr, updated_source_with_net_arr_logic.duo_net_arr, updated_source_with_net_arr_logic.days_in_sao, updated_source_with_net_arr_logic.new_logo_count, updated_source_with_net_arr_logic.user_geo_stamped, updated_source_with_net_arr_logic.user_region_stamped, updated_source_with_net_arr_logic.user_area_stamped, updated_source_with_net_arr_logic.crm_opp_owner_user_role_type_stamped, updated_source_with_net_arr_logic.user_business_unit_stamped, updated_source_with_net_arr_logic.crm_opp_owner_stamped_name, updated_source_with_net_arr_logic.crm_account_owner_stamped_name, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_geo_region_area_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_geo_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_region_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_area_stamped, updated_source_with_net_arr_logic.opportunity_category, updated_source_with_net_arr_logic.opportunity_health, updated_source_with_net_arr_logic.number_of_sa_activity_tasks, updated_source_with_net_arr_logic.risk_type, updated_source_with_net_arr_logic.risk_reasons, updated_source_with_net_arr_logic.tam_notes, updated_source_with_net_arr_logic.primary_solution_architect, updated_source_with_net_arr_logic.product_details, updated_source_with_net_arr_logic.product_category, updated_source_with_net_arr_logic.products_purchased, updated_source_with_net_arr_logic.payment_schedule, updated_source_with_net_arr_logic.comp_new_logo_override, updated_source_with_net_arr_logic.is_pipeline_created_eligible, updated_source_with_net_arr_logic.next_steps, updated_source_with_net_arr_logic.auto_renewal_status, updated_source_with_net_arr_logic.qsr_notes, updated_source_with_net_arr_logic.qsr_status, updated_source_with_net_arr_logic.manager_confidence, updated_source_with_net_arr_logic.renewal_risk_category, updated_source_with_net_arr_logic.renewal_swing_arr, updated_source_with_net_arr_logic.renewal_manager, updated_source_with_net_arr_logic.renewal_forecast_health, updated_source_with_net_arr_logic.startup_type, updated_source_with_net_arr_logic.days_in_0_pending_acceptance, updated_source_with_net_arr_logic.days_in_1_discovery, updated_source_with_net_arr_logic.days_in_2_scoping, updated_source_with_net_arr_logic.days_in_3_technical_evaluation, updated_source_with_net_arr_logic.days_in_4_proposal, updated_source_with_net_arr_logic.days_in_5_negotiating, updated_source_with_net_arr_logic.stage_0_pending_acceptance_date, updated_source_with_net_arr_logic.stage_1_discovery_date, updated_source_with_net_arr_logic.stage_2_scoping_date, updated_source_with_net_arr_logic.stage_3_technical_evaluation_date, updated_source_with_net_arr_logic.stage_4_proposal_date, updated_source_with_net_arr_logic.stage_5_negotiating_date, updated_source_with_net_arr_logic.stage_6_awaiting_signature_date, updated_source_with_net_arr_logic.stage_6_closed_won_date, updated_source_with_net_arr_logic.stage_6_closed_lost_date, updated_source_with_net_arr_logic.dr_partner_deal_type, updated_source_with_net_arr_logic.dr_partner_engagement, updated_source_with_net_arr_logic.dr_deal_id, updated_source_with_net_arr_logic.dr_primary_registration, updated_source_with_net_arr_logic.partner_account, updated_source_with_net_arr_logic.dr_status, updated_source_with_net_arr_logic.distributor, updated_source_with_net_arr_logic.influence_partner, updated_source_with_net_arr_logic.is_focus_partner, updated_source_with_net_arr_logic.fulfillment_partner, updated_source_with_net_arr_logic.platform_partner, updated_source_with_net_arr_logic.partner_track, updated_source_with_net_arr_logic.resale_partner_track, updated_source_with_net_arr_logic.is_public_sector_opp, updated_source_with_net_arr_logic.is_registration_from_portal, updated_source_with_net_arr_logic.calculated_discount, updated_source_with_net_arr_logic.partner_discount, updated_source_with_net_arr_logic.partner_discount_calc, updated_source_with_net_arr_logic.partner_margin_percentage, updated_source_with_net_arr_logic.comp_channel_neutral, updated_source_with_net_arr_logic.aggregate_partner, updated_source_with_net_arr_logic.cp_champion, updated_source_with_net_arr_logic.cp_close_plan, updated_source_with_net_arr_logic.cp_decision_criteria, updated_source_with_net_arr_logic.cp_decision_process, updated_source_with_net_arr_logic.cp_economic_buyer, updated_source_with_net_arr_logic.cp_help, updated_source_with_net_arr_logic.cp_identify_pain, updated_source_with_net_arr_logic.cp_metrics, updated_source_with_net_arr_logic.cp_partner, updated_source_with_net_arr_logic.cp_paper_process, updated_source_with_net_arr_logic.cp_review_notes, updated_source_with_net_arr_logic.cp_risks, updated_source_with_net_arr_logic.cp_use_cases, updated_source_with_net_arr_logic.cp_value_driver, updated_source_with_net_arr_logic.cp_why_do_anything_at_all, updated_source_with_net_arr_logic.cp_why_gitlab, updated_source_with_net_arr_logic.cp_why_now, updated_source_with_net_arr_logic.cp_score, updated_source_with_net_arr_logic.sa_tech_evaluation_close_status, updated_source_with_net_arr_logic.sa_tech_evaluation_end_date, updated_source_with_net_arr_logic.sa_tech_evaluation_start_date, updated_source_with_net_arr_logic.fpa_master_bookings_flag, updated_source_with_net_arr_logic.downgrade_reason, updated_source_with_net_arr_logic.ssp_id, updated_source_with_net_arr_logic.ga_client_id, updated_source_with_net_arr_logic.vsa_readout, updated_source_with_net_arr_logic.vsa_start_date_net_arr, updated_source_with_net_arr_logic.vsa_start_date, updated_source_with_net_arr_logic.vsa_url, updated_source_with_net_arr_logic.vsa_status, updated_source_with_net_arr_logic.vsa_end_date, updated_source_with_net_arr_logic.downgrade_details, updated_source_with_net_arr_logic.won_arr_basis_for_clari, updated_source_with_net_arr_logic.arr_basis_for_clari, updated_source_with_net_arr_logic.forecasted_churn_for_clari, updated_source_with_net_arr_logic.override_arr_basis_clari, updated_source_with_net_arr_logic.intended_product_tier, updated_source_with_net_arr_logic.ptc_predicted_arr, updated_source_with_net_arr_logic.ptc_predicted_renewal_risk_category, updated_source_with_net_arr_logic.is_deleted, updated_source_with_net_arr_logic.last_activity_date, updated_source_with_net_arr_logic.sales_last_activity_date, updated_source_with_net_arr_logic.record_type_id, updated_source_with_net_arr_logic.dbt_scd_id, updated_source_with_net_arr_logic.dbt_updated_at, updated_source_with_net_arr_logic.dbt_valid_from, updated_source_with_net_arr_logic.dbt_valid_to, opportunity_deal_size, arr_created_date_id, created_date_id, sales_accepted_date_id, close_date_id, stage_0_pending_acceptance_date_id, stage_1_discovery_date_id, stage_2_scoping_date_id, stage_3_technical_evaluation_date_id, stage_4_proposal_date_id, stage_5_negotiating_date_id, stage_6_awaiting_signature_date_id, stage_6_closed_won_date_id, stage_6_closed_lost_date_id, technical_evaluation_date_id, last_activity_date_id, sales_last_activity_date_id, subscription_start_date_id, subscription_end_date_id, sales_qualified_date_id, dim_crm_opportunity_id, dim_crm_user_id, dim_crm_account_id, dim_parent_crm_opportunity_id, arr_created_date, crm_opp_owner_geo_stamped, crm_opp_owner_region_stamped, crm_opp_owner_area_stamped, crm_opp_owner_business_unit_stamped, raw_net_arr, order_type, opportunity_term_base, days_since_last_activity, created_date, sales_accepted_date, close_date, days_in_stage, close_fiscal_year, net_new_source_categories, source_buckets, deal_path, sales_qualified_source, sales_qualified_source_grouped, sqs_bucket_engagement, order_type_grouped, growth_type, user_segment_stamped, user_segment_region_stamped_grouped, user_segment_geo_region_area_stamped, crm_opp_owner_sales_segment_stamped, user_segment_stamped_grouped, crm_opp_owner_sales_segment_geo_region_area_stamped, sao_crm_opp_owner_sales_segment_stamped_grouped, sao_crm_opp_owner_segment_region_stamped_grouped, sales_segment, parent_segment, division_sales_segment_stamped, channel_type, is_open, is_risky, is_stage_1_plus, is_stage_3_plus, is_stage_4_plus, is_lost, is_renewal, is_duplicate, is_comp_new_logo_override, is_closed_deals, closed_buckets, sdr_or_bdr, reason_for_loss_staged, reason_for_loss_calc, stage_name_3plus, stage_name_4plus, competitors_other_flag, competitors_gitlab_core_flag, competitors_none_flag, competitors_github_enterprise_flag, competitors_bitbucket_server_flag, competitors_unknown_flag, competitors_github_flag, competitors_gitlab_flag, competitors_jenkins_flag, competitors_azure_devops_flag, competitors_svn_flag, competitors_bitbucket_flag, competitors_atlassian_flag, competitors_perforce_flag, competitors_visual_studio_flag, competitors_azure_flag, competitors_amazon_code_commit_flag, competitors_circleci_flag, competitors_bamboo_flag, competitors_aws_flag, _last_dbt_run.
  compiled code at target/run/gitlab_snowflake/models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql
```

**Comment by DanCodedThis** [comment]
@osmazur Can you take a look? Check dbt-gitlab on this branch? `cargo run --release`

File: crates/core-executor/src/datafusion/logical_analyzer/like_type_analyzer.rs [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+use datafusion_common::config::ConfigOptions;
+use datafusion_common::tree_node::{Transformed, TransformedResult, TreeNode};
+use datafusion_expr::expr::ScalarFunction;
+use datafusion_expr::expr_rewriter::NamePreserver;
+use datafusion_expr::{Expr, ExprSchemable, Like, ScalarUDF};
+use embucket_functions::conversion::ToVarcharFunc;
+use std::fmt::Debug;
+use std::sync::Arc;
+
+/// TODO DOCS
```
Comment (osipovartem) [inline crates/core-executor/src/datafusion/logical_analyzer/like_type_analyzer.rs]: Maybe fix (add docs)

File: crates/core-executor/src/datafusion/logical_analyzer/mod.rs [hunk 2]
```diff
@@ -4,20 +4,32 @@ use std::sync::Arc;
...
         Arc::new(iceberg_types_analyzer::IcebergTypesAnalyzer {}),
         Arc::new(cast_analyzer::CastAnalyzer::new(session_params)),
         // Must be registered after CastAnalyzer because it introduces function calls
         // that can change the schema
         Arc::new(union_schema_analyzer::UnionSchemaAnalyzer::new()),
     ];
-    base_rules.extend(rules);
-    base_rules
+
+    let mut rules: Vec<Arc<dyn AnalyzerRule + Send + Sync>> = vec![];
```
Comment (osipovartem) [inline crates/core-executor/src/datafusion/logical_analyzer/mod.rs]: just extend before_base_rules

Comment (DanCodedThis) [reply crates/core-executor/src/datafusion/logical_analyzer/mod.rs]: It was originally like that, I'll revert, just wanted to be more clear about rule ordering

**Comment by DanCodedThis** [comment]
> P.S. After fix, we reduced our type_coersion errors in half (was 8 now 4), but it added additionally 8 new errors (from passed I assume) which appears to fail on the rule. But actually, if you take a look, they fail because of schema name mismatch. For exmaple:
> 
> ```
> �[0m18:06:11    Database Error in model prep_crm_opportunity_calcs (models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql)
>   010001 (02000): LikeILikeTypeAnalyzer
>   caused by
>   Schema error: No field named updated_source_with_net_arr_logic.sales_segmentation_employees. Valid fields are updated_source_with_net_arr_logic.opportunity_name, updated_source_with_net_arr_logic.is_closed, updated_source_with_net_arr_logic.valid_deal_count, updated_source_with_net_arr_logic.deployment_preference, updated_source_with_net_arr_logic.generated_source, updated_source_with_net_arr_logic.lead_source, updated_source_with_net_arr_logic.merged_opportunity_id, updated_source_with_net_arr_logic.duplicate_opportunity_id, updated_source_with_net_arr_logic.contract_reset_opportunity_id, updated_source_with_net_arr_logic.account_owner, updated_source_with_net_arr_logic.opportunity_owner, updated_source_with_net_arr_logic.opportunity_owner_manager, updated_source_with_net_arr_logic.opportunity_owner_department, updated_source_with_net_arr_logic.crm_sales_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id_lookup, updated_source_with_net_arr_logic.opportunity_development_representative, updated_source_with_net_arr_logic.sales_path, updated_source_with_net_arr_logic.sales_qualified_date, updated_source_with_net_arr_logic.iqm_submitted_by_role, updated_source_with_net_arr_logic.subscription_type, updated_source_with_net_arr_logic.stage_name, updated_source_with_net_arr_logic.acv, updated_source_with_net_arr_logic.amount, updated_source_with_net_arr_logic.competitors, updated_source_with_net_arr_logic.critical_deal_flag, updated_source_with_net_arr_logic.forecast_category_name, updated_source_with_net_arr_logic.forecasted_iacv, updated_source_with_net_arr_logic.iacv_created_date, updated_source_with_net_arr_logic.incremental_acv, updated_source_with_net_arr_logic.invoice_number, updated_source_with_net_arr_logic.is_refund, updated_source_with_net_arr_logic.is_downgrade, updated_source_with_net_arr_logic.is_swing_deal, updated_source_with_net_arr_logic.is_edu_oss, updated_source_with_net_arr_logic.is_ps_opp, updated_source_with_net_arr_logic.net_incremental_acv, updated_source_with_net_arr_logic.primary_campaign_source_id, updated_source_with_net_arr_logic.probability, updated_source_with_net_arr_logic.professional_services_value, updated_source_with_net_arr_logic.edu_services_value, updated_source_with_net_arr_logic.investment_services_value, updated_source_with_net_arr_logic.pushed_count, updated_source_with_net_arr_logic.reason_for_loss, updated_source_with_net_arr_logic.reason_for_loss_details, updated_source_with_net_arr_logic.refund_iacv, updated_source_with_net_arr_logic.downgrade_iacv, updated_source_with_net_arr_logic.renewal_acv, updated_source_with_net_arr_logic.renewal_amount, updated_source_with_net_arr_logic.sdr_pipeline_contribution, updated_source_with_net_arr_logic.solutions_to_be_replaced, updated_source_with_net_arr_logic.technical_evaluation_date, updated_source_with_net_arr_logic.total_contract_value, updated_source_with_net_arr_logic.recurring_amount, updated_source_with_net_arr_logic.true_up_amount, updated_source_with_net_arr_logic.proserv_amount, updated_source_with_net_arr_logic.other_non_recurring_amount, updated_source_with_net_arr_logic.upside_swing_deal_iacv, updated_source_with_net_arr_logic.is_web_portal_purchase, updated_source_with_net_arr_logic.partner_initiated_opportunity, updated_source_with_net_arr_logic.user_segment, updated_source_with_net_arr_logic.subscription_start_date, updated_source_with_net_arr_logic.subscription_end_date, updated_source_with_net_arr_logic.subscription_renewal_date, updated_source_with_net_arr_logic.true_up_value, updated_source_with_net_arr_logic.order_type_current, updated_source_with_net_arr_logic.arr_basis, updated_source_with_net_arr_logic.arr, updated_source_with_net_arr_logic.xdr_net_arr_stage_3, updated_source_with_net_arr_logic.xdr_net_arr_stage_1, updated_source_with_net_arr_logic.net_arr_stage_1, updated_source_with_net_arr_logic.enterprise_agile_planning_net_arr, updated_source_with_net_arr_logic.duo_net_arr, updated_source_with_net_arr_logic.days_in_sao, updated_source_with_net_arr_logic.new_logo_count, updated_source_with_net_arr_logic.user_geo_stamped, updated_source_with_net_arr_logic.user_region_stamped, updated_source_with_net_arr_logic.user_area_stamped, updated_source_with_net_arr_logic.crm_opp_owner_user_role_type_stamped, updated_source_with_net_arr_logic.user_business_unit_stamped, updated_source_with_net_arr_logic.crm_opp_owner_stamped_name, updated_source_with_net_arr_logic.crm_account_owner_stamped_name, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_geo_region_area_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_geo_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_region_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_area_stamped, updated_source_with_net_arr_logic.opportunity_category, updated_source_with_net_arr_logic.opportunity_health, updated_source_with_net_arr_logic.number_of_sa_activity_tasks, updated_source_with_net_arr_logic.risk_type, updated_source_with_net_arr_logic.risk_reasons, updated_source_with_net_arr_logic.tam_notes, updated_source_with_net_arr_logic.primary_solution_architect, updated_source_with_net_arr_logic.product_details, updated_source_with_net_arr_logic.product_category, updated_source_with_net_arr_logic.products_purchased, updated_source_with_net_arr_logic.payment_schedule, updated_source_with_net_arr_logic.comp_new_logo_override, updated_source_with_net_arr_logic.is_pipeline_created_eligible, updated_source_with_net_arr_logic.next_steps, updated_source_with_net_arr_logic.auto_renewal_status, updated_source_with_net_arr_logic.qsr_notes, updated_source_with_net_arr_logic.qsr_status, updated_source_with_net_arr_logic.manager_confidence, updated_source_with_net_arr_logic.renewal_risk_category, updated_source_with_net_arr_logic.renewal_swing_arr, updated_source_with_net_arr_logic.renewal_manager, updated_source_with_net_arr_logic.renewal_forecast_health, updated_source_with_net_arr_logic.startup_type, updated_source_with_net_arr_logic.days_in_0_pending_acceptance, updated_source_with_net_arr_logic.days_in_1_discovery, updated_source_with_net_arr_logic.days_in_2_scoping, updated_source_with_net_arr_logic.days_in_3_technical_evaluation, updated_source_with_net_arr_logic.days_in_4_proposal, updated_source_with_net_arr_logic.days_in_5_negotiating, updated_source_with_net_arr_logic.stage_0_pending_acceptance_date, updated_source_with_net_arr_logic.stage_1_discovery_date, updated_source_with_net_arr_logic.stage_2_scoping_date, updated_source_with_net_arr_logic.stage_3_technical_evaluation_date, updated_source_with_net_arr_logic.stage_4_proposal_date, updated_source_with_net_arr_logic.stage_5_negotiating_date, updated_source_with_net_arr_logic.stage_6_awaiting_signature_date, updated_source_with_net_arr_logic.stage_6_closed_won_date, updated_source_with_net_arr_logic.stage_6_closed_lost_date, updated_source_with_net_arr_logic.dr_partner_deal_type, updated_source_with_net_arr_logic.dr_partner_engagement, updated_source_with_net_arr_logic.dr_deal_id, updated_source_with_net_arr_logic.dr_primary_registration, updated_source_with_net_arr_logic.partner_account, updated_source_with_net_arr_logic.dr_status, updated_source_with_net_arr_logic.distributor, updated_source_with_net_arr_logic.influence_partner, updated_source_with_net_arr_logic.is_focus_partner, updated_source_with_net_arr_logic.fulfillment_partner, updated_source_with_net_arr_logic.platform_partner, updated_source_with_net_arr_logic.partner_track, updated_source_with_net_arr_logic.resale_partner_track, updated_source_with_net_arr_logic.is_public_sector_opp, updated_source_with_net_arr_logic.is_registration_from_portal, updated_source_with_net_arr_logic.calculated_discount, updated_source_with_net_arr_logic.partner_discount, updated_source_with_net_arr_logic.partner_discount_calc, updated_source_with_net_arr_logic.partner_margin_percentage, updated_source_with_net_arr_logic.comp_channel_neutral, updated_source_with_net_arr_logic.aggregate_partner, updated_source_with_net_arr_logic.cp_champion, updated_source_with_net_arr_logic.cp_close_plan, updated_source_with_net_arr_logic.cp_decision_criteria, updated_source_with_net_arr_logic.cp_decision_process, updated_source_with_net_arr_logic.cp_economic_buyer, updated_source_with_net_arr_logic.cp_help, updated_source_with_net_arr_logic.cp_identify_pain, updated_source_with_net_arr_logic.cp_metrics, updated_source_with_net_arr_logic.cp_partner, updated_source_with_net_arr_logic.cp_paper_process, updated_source_with_net_arr_logic.cp_review_notes, updated_source_with_net_arr_logic.cp_risks, updated_source_with_net_arr_logic.cp_use_cases, updated_source_with_net_arr_logic.cp_value_driver, updated_source_with_net_arr_logic.cp_why_do_anything_at_all, updated_source_with_net_arr_logic.cp_why_gitlab, updated_source_with_net_arr_logic.cp_why_now, updated_source_with_net_arr_logic.cp_score, updated_source_with_net_arr_logic.sa_tech_evaluation_close_status, updated_source_with_net_arr_logic.sa_tech_evaluation_end_date, updated_source_with_net_arr_logic.sa_tech_evaluation_start_date, updated_source_with_net_arr_logic.fpa_master_bookings_flag, updated_source_with_net_arr_logic.downgrade_reason, updated_source_with_net_arr_logic.ssp_id, updated_source_with_net_arr_logic.ga_client_id, updated_source_with_net_arr_logic.vsa_readout, updated_source_with_net_arr_logic.vsa_start_date_net_arr, updated_source_with_net_arr_logic.vsa_start_date, updated_source_with_net_arr_logic.vsa_url, updated_source_with_net_arr_logic.vsa_status, updated_source_with_net_arr_logic.vsa_end_date, updated_source_with_net_arr_logic.downgrade_details, updated_source_with_net_arr_logic.won_arr_basis_for_clari, updated_source_with_net_arr_logic.arr_basis_for_clari, updated_source_with_net_arr_logic.forecasted_churn_for_clari, updated_source_with_net_arr_logic.override_arr_basis_clari, updated_source_with_net_arr_logic.intended_product_tier, updated_source_with_net_arr_logic.ptc_predicted_arr, updated_source_with_net_arr_logic.ptc_predicted_renewal_risk_category, updated_source_with_net_arr_logic.is_deleted, updated_source_with_net_arr_logic.last_activity_date, updated_source_with_net_arr_logic.sales_last_activity_date, updated_source_with_net_arr_logic.record_type_id, updated_source_with_net_arr_logic.dbt_scd_id, updated_source_with_net_arr_logic.dbt_updated_at, updated_source_with_net_arr_logic.dbt_valid_from, updated_source_with_net_arr_logic.dbt_valid_to, opportunity_deal_size, arr_created_date_id, created_date_id, sales_accepted_date_id, close_date_id, stage_0_pending_acceptance_date_id, stage_1_discovery_date_id, stage_2_scoping_date_id, stage_3_technical_evaluation_date_id, stage_4_proposal_date_id, stage_5_negotiating_date_id, stage_6_awaiting_signature_date_id, stage_6_closed_won_date_id, stage_6_closed_lost_date_id, technical_evaluation_date_id, last_activity_date_id, sales_last_activity_date_id, subscription_start_date_id, subscription_end_date_id, sales_qualified_date_id, dim_crm_opportunity_id, dim_crm_user_id, dim_crm_account_id, dim_parent_crm_opportunity_id, arr_created_date, crm_opp_owner_geo_stamped, crm_opp_owner_region_stamped, crm_opp_owner_area_stamped, crm_opp_owner_business_unit_stamped, raw_net_arr, order_type, opportunity_term_base, days_since_last_activity, created_date, sales_accepted_date, close_date, days_in_stage, close_fiscal_year, net_new_source_categories, source_buckets, deal_path, sales_qualified_source, sales_qualified_source_grouped, sqs_bucket_engagement, order_type_grouped, growth_type, user_segment_stamped, user_segment_region_stamped_grouped, user_segment_geo_region_area_stamped, crm_opp_owner_sales_segment_stamped, user_segment_stamped_grouped, crm_opp_owner_sales_segment_geo_region_area_stamped, sao_crm_opp_owner_sales_segment_stamped_grouped, sao_crm_opp_owner_segment_region_stamped_grouped, sales_segment, parent_segment, division_sales_segment_stamped, channel_type, is_open, is_risky, is_stage_1_plus, is_stage_3_plus, is_stage_4_plus, is_lost, is_renewal, is_duplicate, is_comp_new_logo_override, is_closed_deals, closed_buckets, sdr_or_bdr, reason_for_loss_staged, reason_for_loss_calc, stage_name_3plus, stage_name_4plus, competitors_other_flag, competitors_gitlab_core_flag, competitors_none_flag, competitors_github_enterprise_flag, competitors_bitbucket_server_flag, competitors_unknown_flag, competitors_github_flag, competitors_gitlab_flag, competitors_jenkins_flag, competitors_azure_devops_flag, competitors_svn_flag, competitors_bitbucket_flag, competitors_atlassian_flag, competitors_perforce_flag, competitors_visual_studio_flag, competitors_azure_flag, competitors_amazon_code_commit_flag, competitors_circleci_flag, competitors_bamboo_flag, competitors_aws_flag, _last_dbt_run.
>   compiled code at target/run/gitlab_snowflake/models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql
> ```

It may perhaps fail because of me using the schema to resolve the datatype (which is easier then matching by hand).

**Comment by DanCodedThis** [comment]
> > P.S. After fix, we reduced our type_coersion errors in half (was 8 now 4), but it added additionally 8 new errors (from passed I assume) which appears to fail on the rule. But actually, if you take a look, they fail because of schema name mismatch. For exmaple:
> > ```
> > �[0m18:06:11    Database Error in model prep_crm_opportunity_calcs (models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql)
> >   010001 (02000): LikeILikeTypeAnalyzer
> >   caused by
> >   Schema error: No field named updated_source_with_net_arr_logic.sales_segmentation_employees. Valid fields are updated_source_with_net_arr_logic.opportunity_name, updated_source_with_net_arr_logic.is_closed, updated_source_with_net_arr_logic.valid_deal_count, updated_source_with_net_arr_logic.deployment_preference, updated_source_with_net_arr_logic.generated_source, updated_source_with_net_arr_logic.lead_source, updated_source_with_net_arr_logic.merged_opportunity_id, updated_source_with_net_arr_logic.duplicate_opportunity_id, updated_source_with_net_arr_logic.contract_reset_opportunity_id, updated_source_with_net_arr_logic.account_owner, updated_source_with_net_arr_logic.opportunity_owner, updated_source_with_net_arr_logic.opportunity_owner_manager, updated_source_with_net_arr_logic.opportunity_owner_department, updated_source_with_net_arr_logic.crm_sales_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id_lookup, updated_source_with_net_arr_logic.opportunity_development_representative, updated_source_with_net_arr_logic.sales_path, updated_source_with_net_arr_logic.sales_qualified_date, updated_source_with_net_arr_logic.iqm_submitted_by_role, updated_source_with_net_arr_logic.subscription_type, updated_source_with_net_arr_logic.stage_name, updated_source_with_net_arr_logic.acv, updated_source_with_net_arr_logic.amount, updated_source_with_net_arr_logic.competitors, updated_source_with_net_arr_logic.critical_deal_flag, updated_source_with_net_arr_logic.forecast_category_name, updated_source_with_net_arr_logic.forecasted_iacv, updated_source_with_net_arr_logic.iacv_created_date, updated_source_with_net_arr_logic.incremental_acv, updated_source_with_net_arr_logic.invoice_number, updated_source_with_net_arr_logic.is_refund, updated_source_with_net_arr_logic.is_downgrade, updated_source_with_net_arr_logic.is_swing_deal, updated_source_with_net_arr_logic.is_edu_oss, updated_source_with_net_arr_logic.is_ps_opp, updated_source_with_net_arr_logic.net_incremental_acv, updated_source_with_net_arr_logic.primary_campaign_source_id, updated_source_with_net_arr_logic.probability, updated_source_with_net_arr_logic.professional_services_value, updated_source_with_net_arr_logic.edu_services_value, updated_source_with_net_arr_logic.investment_services_value, updated_source_with_net_arr_logic.pushed_count, updated_source_with_net_arr_logic.reason_for_loss, updated_source_with_net_arr_logic.reason_for_loss_details, updated_source_with_net_arr_logic.refund_iacv, updated_source_with_net_arr_logic.downgrade_iacv, updated_source_with_net_arr_logic.renewal_acv, updated_source_with_net_arr_logic.renewal_amount, updated_source_with_net_arr_logic.sdr_pipeline_contribution, updated_source_with_net_arr_logic.solutions_to_be_replaced, updated_source_with_net_arr_logic.technical_evaluation_date, updated_source_with_net_arr_logic.total_contract_value, updated_source_with_net_arr_logic.recurring_amount, updated_source_with_net_arr_logic.true_up_amount, updated_source_with_net_arr_logic.proserv_amount, updated_source_with_net_arr_logic.other_non_recurring_amount, updated_source_with_net_arr_logic.upside_swing_deal_iacv, updated_source_with_net_arr_logic.is_web_portal_purchase, updated_source_with_net_arr_logic.partner_initiated_opportunity, updated_source_with_net_arr_logic.user_segment, updated_source_with_net_arr_logic.subscription_start_date, updated_source_with_net_arr_logic.subscription_end_date, updated_source_with_net_arr_logic.subscription_renewal_date, updated_source_with_net_arr_logic.true_up_value, updated_source_with_net_arr_logic.order_type_current, updated_source_with_net_arr_logic.arr_basis, updated_source_with_net_arr_logic.arr, updated_source_with_net_arr_logic.xdr_net_arr_stage_3, updated_source_with_net_arr_logic.xdr_net_arr_stage_1, updated_source_with_net_arr_logic.net_arr_stage_1, updated_source_with_net_arr_logic.enterprise_agile_planning_net_arr, updated_source_with_net_arr_logic.duo_net_arr, updated_source_with_net_arr_logic.days_in_sao, updated_source_with_net_arr_logic.new_logo_count, updated_source_with_net_arr_logic.user_geo_stamped, updated_source_with_net_arr_logic.user_region_stamped, updated_source_with_net_arr_logic.user_area_stamped, updated_source_with_net_arr_logic.crm_opp_owner_user_role_type_stamped, updated_source_with_net_arr_logic.user_business_unit_stamped, updated_source_with_net_arr_logic.crm_opp_owner_stamped_name, updated_source_with_net_arr_logic.crm_account_owner_stamped_name, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_geo_region_area_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_geo_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_region_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_area_stamped, updated_source_with_net_arr_logic.opportunity_category, updated_source_with_net_arr_logic.opportunity_health, updated_source_with_net_arr_logic.number_of_sa_activity_tasks, updated_source_with_net_arr_logic.risk_type, updated_source_with_net_arr_logic.risk_reasons, updated_source_with_net_arr_logic.tam_notes, updated_source_with_net_arr_logic.primary_solution_architect, updated_source_with_net_arr_logic.product_details, updated_source_with_net_arr_logic.product_category, updated_source_with_net_arr_logic.products_purchased, updated_source_with_net_arr_logic.payment_schedule, updated_source_with_net_arr_logic.comp_new_logo_override, updated_source_with_net_arr_logic.is_pipeline_created_eligible, updated_source_with_net_arr_logic.next_steps, updated_source_with_net_arr_logic.auto_renewal_status, updated_source_with_net_arr_logic.qsr_notes, updated_source_with_net_arr_logic.qsr_status, updated_source_with_net_arr_logic.manager_confidence, updated_source_with_net_arr_logic.renewal_risk_category, updated_source_with_net_arr_logic.renewal_swing_arr, updated_source_with_net_arr_logic.renewal_manager, updated_source_with_net_arr_logic.renewal_forecast_health, updated_source_with_net_arr_logic.startup_type, updated_source_with_net_arr_logic.days_in_0_pending_acceptance, updated_source_with_net_arr_logic.days_in_1_discovery, updated_source_with_net_arr_logic.days_in_2_scoping, updated_source_with_net_arr_logic.days_in_3_technical_evaluation, updated_source_with_net_arr_logic.days_in_4_proposal, updated_source_with_net_arr_logic.days_in_5_negotiating, updated_source_with_net_arr_logic.stage_0_pending_acceptance_date, updated_source_with_net_arr_logic.stage_1_discovery_date, updated_source_with_net_arr_logic.stage_2_scoping_date, updated_source_with_net_arr_logic.stage_3_technical_evaluation_date, updated_source_with_net_arr_logic.stage_4_proposal_date, updated_source_with_net_arr_logic.stage_5_negotiating_date, updated_source_with_net_arr_logic.stage_6_awaiting_signature_date, updated_source_with_net_arr_logic.stage_6_closed_won_date, updated_source_with_net_arr_logic.stage_6_closed_lost_date, updated_source_with_net_arr_logic.dr_partner_deal_type, updated_source_with_net_arr_logic.dr_partner_engagement, updated_source_with_net_arr_logic.dr_deal_id, updated_source_with_net_arr_logic.dr_primary_registration, updated_source_with_net_arr_logic.partner_account, updated_source_with_net_arr_logic.dr_status, updated_source_with_net_arr_logic.distributor, updated_source_with_net_arr_logic.influence_partner, updated_source_with_net_arr_logic.is_focus_partner, updated_source_with_net_arr_logic.fulfillment_partner, updated_source_with_net_arr_logic.platform_partner, updated_source_with_net_arr_logic.partner_track, updated_source_with_net_arr_logic.resale_partner_track, updated_source_with_net_arr_logic.is_public_sector_opp, updated_source_with_net_arr_logic.is_registration_from_portal, updated_source_with_net_arr_logic.calculated_discount, updated_source_with_net_arr_logic.partner_discount, updated_source_with_net_arr_logic.partner_discount_calc, updated_source_with_net_arr_logic.partner_margin_percentage, updated_source_with_net_arr_logic.comp_channel_neutral, updated_source_with_net_arr_logic.aggregate_partner, updated_source_with_net_arr_logic.cp_champion, updated_source_with_net_arr_logic.cp_close_plan, updated_source_with_net_arr_logic.cp_decision_criteria, updated_source_with_net_arr_logic.cp_decision_process, updated_source_with_net_arr_logic.cp_economic_buyer, updated_source_with_net_arr_logic.cp_help, updated_source_with_net_arr_logic.cp_identify_pain, updated_source_with_net_arr_logic.cp_metrics, updated_source_with_net_arr_logic.cp_partner, updated_source_with_net_arr_logic.cp_paper_process, updated_source_with_net_arr_logic.cp_review_notes, updated_source_with_net_arr_logic.cp_risks, updated_source_with_net_arr_logic.cp_use_cases, updated_source_with_net_arr_logic.cp_value_driver, updated_source_with_net_arr_logic.cp_why_do_anything_at_all, updated_source_with_net_arr_logic.cp_why_gitlab, updated_source_with_net_arr_logic.cp_why_now, updated_source_with_net_arr_logic.cp_score, updated_source_with_net_arr_logic.sa_tech_evaluation_close_status, updated_source_with_net_arr_logic.sa_tech_evaluation_end_date, updated_source_with_net_arr_logic.sa_tech_evaluation_start_date, updated_source_with_net_arr_logic.fpa_master_bookings_flag, updated_source_with_net_arr_logic.downgrade_reason, updated_source_with_net_arr_logic.ssp_id, updated_source_with_net_arr_logic.ga_client_id, updated_source_with_net_arr_logic.vsa_readout, updated_source_with_net_arr_logic.vsa_start_date_net_arr, updated_source_with_net_arr_logic.vsa_start_date, updated_source_with_net_arr_logic.vsa_url, updated_source_with_net_arr_logic.vsa_status, updated_source_with_net_arr_logic.vsa_end_date, updated_source_with_net_arr_logic.downgrade_details, updated_source_with_net_arr_logic.won_arr_basis_for_clari, updated_source_with_net_arr_logic.arr_basis_for_clari, updated_source_with_net_arr_logic.forecasted_churn_for_clari, updated_source_with_net_arr_logic.override_arr_basis_clari, updated_source_with_net_arr_logic.intended_product_tier, updated_source_with_net_arr_logic.ptc_predicted_arr, updated_source_with_net_arr_logic.ptc_predicted_renewal_risk_category, updated_source_with_net_arr_logic.is_deleted, updated_source_with_net_arr_logic.last_activity_date, updated_source_with_net_arr_logic.sales_last_activity_date, updated_source_with_net_arr_logic.record_type_id, updated_source_with_net_arr_logic.dbt_scd_id, updated_source_with_net_arr_logic.dbt_updated_at, updated_source_with_net_arr_logic.dbt_valid_from, updated_source_with_net_arr_logic.dbt_valid_to, opportunity_deal_size, arr_created_date_id, created_date_id, sales_accepted_date_id, close_date_id, stage_0_pending_acceptance_date_id, stage_1_discovery_date_id, stage_2_scoping_date_id, stage_3_technical_evaluation_date_id, stage_4_proposal_date_id, stage_5_negotiating_date_id, stage_6_awaiting_signature_date_id, stage_6_closed_won_date_id, stage_6_closed_lost_date_id, technical_evaluation_date_id, last_activity_date_id, sales_last_activity_date_id, subscription_start_date_id, subscription_end_date_id, sales_qualified_date_id, dim_crm_opportunity_id, dim_crm_user_id, dim_crm_account_id, dim_parent_crm_opportunity_id, arr_created_date, crm_opp_owner_geo_stamped, crm_opp_owner_region_stamped, crm_opp_owner_area_stamped, crm_opp_owner_business_unit_stamped, raw_net_arr, order_type, opportunity_term_base, days_since_last_activity, created_date, sales_accepted_date, close_date, days_in_stage, close_fiscal_year, net_new_source_categories, source_buckets, deal_path, sales_qualified_source, sales_qualified_source_grouped, sqs_bucket_engagement, order_type_grouped, growth_type, user_segment_stamped, user_segment_region_stamped_grouped, user_segment_geo_region_area_stamped, crm_opp_owner_sales_segment_stamped, user_segment_stamped_grouped, crm_opp_owner_sales_segment_geo_region_area_stamped, sao_crm_opp_owner_sales_segment_stamped_grouped, sao_crm_opp_owner_segment_region_stamped_grouped, sales_segment, parent_segment, division_sales_segment_stamped, channel_type, is_open, is_risky, is_stage_1_plus, is_stage_3_plus, is_stage_4_plus, is_lost, is_renewal, is_duplicate, is_comp_new_logo_override, is_closed_deals, closed_buckets, sdr_or_bdr, reason_for_loss_staged, reason_for_loss_calc, stage_name_3plus, stage_name_4plus, competitors_other_flag, competitors_gitlab_core_flag, competitors_none_flag, competitors_github_enterprise_flag, competitors_bitbucket_server_flag, competitors_unknown_flag, competitors_github_flag, competitors_gitlab_flag, competitors_jenkins_flag, competitors_azure_devops_flag, competitors_svn_flag, competitors_bitbucket_flag, competitors_atlassian_flag, competitors_perforce_flag, competitors_visual_studio_flag, competitors_azure_flag, competitors_amazon_code_commit_flag, competitors_circleci_flag, competitors_bamboo_flag, competitors_aws_flag, _last_dbt_run.
> >   compiled code at target/run/gitlab_snowflake/models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql
> > ```
> 
> It may perhaps fail because of me using the schema to resolve the datatype (which is easier then matching by hand).

Nope since columns internally don't store datatypes. Either the column was not created by some other error (reason, etc) or the schema recompute I do may be doing this.

**Comment by DanCodedThis** [comment]
> P.S. After fix, we reduced our type_coersion errors in half (was 8 now 4), but it added additionally 8 new errors (from passed I assume) which appears to fail on the rule. But actually, if you take a look, they fail because of schema name mismatch. For exmaple:
> 
> ```
> �[0m18:06:11    Database Error in model prep_crm_opportunity_calcs (models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql)
>   010001 (02000): LikeILikeTypeAnalyzer
>   caused by
>   Schema error: No field named updated_source_with_net_arr_logic.sales_segmentation_employees. Valid fields are updated_source_with_net_arr_logic.opportunity_name, updated_source_with_net_arr_logic.is_closed, updated_source_with_net_arr_logic.valid_deal_count, updated_source_with_net_arr_logic.deployment_preference, updated_source_with_net_arr_logic.generated_source, updated_source_with_net_arr_logic.lead_source, updated_source_with_net_arr_logic.merged_opportunity_id, updated_source_with_net_arr_logic.duplicate_opportunity_id, updated_source_with_net_arr_logic.contract_reset_opportunity_id, updated_source_with_net_arr_logic.account_owner, updated_source_with_net_arr_logic.opportunity_owner, updated_source_with_net_arr_logic.opportunity_owner_manager, updated_source_with_net_arr_logic.opportunity_owner_department, updated_source_with_net_arr_logic.crm_sales_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id, updated_source_with_net_arr_logic.crm_business_dev_rep_id_lookup, updated_source_with_net_arr_logic.opportunity_development_representative, updated_source_with_net_arr_logic.sales_path, updated_source_with_net_arr_logic.sales_qualified_date, updated_source_with_net_arr_logic.iqm_submitted_by_role, updated_source_with_net_arr_logic.subscription_type, updated_source_with_net_arr_logic.stage_name, updated_source_with_net_arr_logic.acv, updated_source_with_net_arr_logic.amount, updated_source_with_net_arr_logic.competitors, updated_source_with_net_arr_logic.critical_deal_flag, updated_source_with_net_arr_logic.forecast_category_name, updated_source_with_net_arr_logic.forecasted_iacv, updated_source_with_net_arr_logic.iacv_created_date, updated_source_with_net_arr_logic.incremental_acv, updated_source_with_net_arr_logic.invoice_number, updated_source_with_net_arr_logic.is_refund, updated_source_with_net_arr_logic.is_downgrade, updated_source_with_net_arr_logic.is_swing_deal, updated_source_with_net_arr_logic.is_edu_oss, updated_source_with_net_arr_logic.is_ps_opp, updated_source_with_net_arr_logic.net_incremental_acv, updated_source_with_net_arr_logic.primary_campaign_source_id, updated_source_with_net_arr_logic.probability, updated_source_with_net_arr_logic.professional_services_value, updated_source_with_net_arr_logic.edu_services_value, updated_source_with_net_arr_logic.investment_services_value, updated_source_with_net_arr_logic.pushed_count, updated_source_with_net_arr_logic.reason_for_loss, updated_source_with_net_arr_logic.reason_for_loss_details, updated_source_with_net_arr_logic.refund_iacv, updated_source_with_net_arr_logic.downgrade_iacv, updated_source_with_net_arr_logic.renewal_acv, updated_source_with_net_arr_logic.renewal_amount, updated_source_with_net_arr_logic.sdr_pipeline_contribution, updated_source_with_net_arr_logic.solutions_to_be_replaced, updated_source_with_net_arr_logic.technical_evaluation_date, updated_source_with_net_arr_logic.total_contract_value, updated_source_with_net_arr_logic.recurring_amount, updated_source_with_net_arr_logic.true_up_amount, updated_source_with_net_arr_logic.proserv_amount, updated_source_with_net_arr_logic.other_non_recurring_amount, updated_source_with_net_arr_logic.upside_swing_deal_iacv, updated_source_with_net_arr_logic.is_web_portal_purchase, updated_source_with_net_arr_logic.partner_initiated_opportunity, updated_source_with_net_arr_logic.user_segment, updated_source_with_net_arr_logic.subscription_start_date, updated_source_with_net_arr_logic.subscription_end_date, updated_source_with_net_arr_logic.subscription_renewal_date, updated_source_with_net_arr_logic.true_up_value, updated_source_with_net_arr_logic.order_type_current, updated_source_with_net_arr_logic.arr_basis, updated_source_with_net_arr_logic.arr, updated_source_with_net_arr_logic.xdr_net_arr_stage_3, updated_source_with_net_arr_logic.xdr_net_arr_stage_1, updated_source_with_net_arr_logic.net_arr_stage_1, updated_source_with_net_arr_logic.enterprise_agile_planning_net_arr, updated_source_with_net_arr_logic.duo_net_arr, updated_source_with_net_arr_logic.days_in_sao, updated_source_with_net_arr_logic.new_logo_count, updated_source_with_net_arr_logic.user_geo_stamped, updated_source_with_net_arr_logic.user_region_stamped, updated_source_with_net_arr_logic.user_area_stamped, updated_source_with_net_arr_logic.crm_opp_owner_user_role_type_stamped, updated_source_with_net_arr_logic.user_business_unit_stamped, updated_source_with_net_arr_logic.crm_opp_owner_stamped_name, updated_source_with_net_arr_logic.crm_account_owner_stamped_name, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_sales_segment_geo_region_area_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_geo_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_region_stamped, updated_source_with_net_arr_logic.sao_crm_opp_owner_area_stamped, updated_source_with_net_arr_logic.opportunity_category, updated_source_with_net_arr_logic.opportunity_health, updated_source_with_net_arr_logic.number_of_sa_activity_tasks, updated_source_with_net_arr_logic.risk_type, updated_source_with_net_arr_logic.risk_reasons, updated_source_with_net_arr_logic.tam_notes, updated_source_with_net_arr_logic.primary_solution_architect, updated_source_with_net_arr_logic.product_details, updated_source_with_net_arr_logic.product_category, updated_source_with_net_arr_logic.products_purchased, updated_source_with_net_arr_logic.payment_schedule, updated_source_with_net_arr_logic.comp_new_logo_override, updated_source_with_net_arr_logic.is_pipeline_created_eligible, updated_source_with_net_arr_logic.next_steps, updated_source_with_net_arr_logic.auto_renewal_status, updated_source_with_net_arr_logic.qsr_notes, updated_source_with_net_arr_logic.qsr_status, updated_source_with_net_arr_logic.manager_confidence, updated_source_with_net_arr_logic.renewal_risk_category, updated_source_with_net_arr_logic.renewal_swing_arr, updated_source_with_net_arr_logic.renewal_manager, updated_source_with_net_arr_logic.renewal_forecast_health, updated_source_with_net_arr_logic.startup_type, updated_source_with_net_arr_logic.days_in_0_pending_acceptance, updated_source_with_net_arr_logic.days_in_1_discovery, updated_source_with_net_arr_logic.days_in_2_scoping, updated_source_with_net_arr_logic.days_in_3_technical_evaluation, updated_source_with_net_arr_logic.days_in_4_proposal, updated_source_with_net_arr_logic.days_in_5_negotiating, updated_source_with_net_arr_logic.stage_0_pending_acceptance_date, updated_source_with_net_arr_logic.stage_1_discovery_date, updated_source_with_net_arr_logic.stage_2_scoping_date, updated_source_with_net_arr_logic.stage_3_technical_evaluation_date, updated_source_with_net_arr_logic.stage_4_proposal_date, updated_source_with_net_arr_logic.stage_5_negotiating_date, updated_source_with_net_arr_logic.stage_6_awaiting_signature_date, updated_source_with_net_arr_logic.stage_6_closed_won_date, updated_source_with_net_arr_logic.stage_6_closed_lost_date, updated_source_with_net_arr_logic.dr_partner_deal_type, updated_source_with_net_arr_logic.dr_partner_engagement, updated_source_with_net_arr_logic.dr_deal_id, updated_source_with_net_arr_logic.dr_primary_registration, updated_source_with_net_arr_logic.partner_account, updated_source_with_net_arr_logic.dr_status, updated_source_with_net_arr_logic.distributor, updated_source_with_net_arr_logic.influence_partner, updated_source_with_net_arr_logic.is_focus_partner, updated_source_with_net_arr_logic.fulfillment_partner, updated_source_with_net_arr_logic.platform_partner, updated_source_with_net_arr_logic.partner_track, updated_source_with_net_arr_logic.resale_partner_track, updated_source_with_net_arr_logic.is_public_sector_opp, updated_source_with_net_arr_logic.is_registration_from_portal, updated_source_with_net_arr_logic.calculated_discount, updated_source_with_net_arr_logic.partner_discount, updated_source_with_net_arr_logic.partner_discount_calc, updated_source_with_net_arr_logic.partner_margin_percentage, updated_source_with_net_arr_logic.comp_channel_neutral, updated_source_with_net_arr_logic.aggregate_partner, updated_source_with_net_arr_logic.cp_champion, updated_source_with_net_arr_logic.cp_close_plan, updated_source_with_net_arr_logic.cp_decision_criteria, updated_source_with_net_arr_logic.cp_decision_process, updated_source_with_net_arr_logic.cp_economic_buyer, updated_source_with_net_arr_logic.cp_help, updated_source_with_net_arr_logic.cp_identify_pain, updated_source_with_net_arr_logic.cp_metrics, updated_source_with_net_arr_logic.cp_partner, updated_source_with_net_arr_logic.cp_paper_process, updated_source_with_net_arr_logic.cp_review_notes, updated_source_with_net_arr_logic.cp_risks, updated_source_with_net_arr_logic.cp_use_cases, updated_source_with_net_arr_logic.cp_value_driver, updated_source_with_net_arr_logic.cp_why_do_anything_at_all, updated_source_with_net_arr_logic.cp_why_gitlab, updated_source_with_net_arr_logic.cp_why_now, updated_source_with_net_arr_logic.cp_score, updated_source_with_net_arr_logic.sa_tech_evaluation_close_status, updated_source_with_net_arr_logic.sa_tech_evaluation_end_date, updated_source_with_net_arr_logic.sa_tech_evaluation_start_date, updated_source_with_net_arr_logic.fpa_master_bookings_flag, updated_source_with_net_arr_logic.downgrade_reason, updated_source_with_net_arr_logic.ssp_id, updated_source_with_net_arr_logic.ga_client_id, updated_source_with_net_arr_logic.vsa_readout, updated_source_with_net_arr_logic.vsa_start_date_net_arr, updated_source_with_net_arr_logic.vsa_start_date, updated_source_with_net_arr_logic.vsa_url, updated_source_with_net_arr_logic.vsa_status, updated_source_with_net_arr_logic.vsa_end_date, updated_source_with_net_arr_logic.downgrade_details, updated_source_with_net_arr_logic.won_arr_basis_for_clari, updated_source_with_net_arr_logic.arr_basis_for_clari, updated_source_with_net_arr_logic.forecasted_churn_for_clari, updated_source_with_net_arr_logic.override_arr_basis_clari, updated_source_with_net_arr_logic.intended_product_tier, updated_source_with_net_arr_logic.ptc_predicted_arr, updated_source_with_net_arr_logic.ptc_predicted_renewal_risk_category, updated_source_with_net_arr_logic.is_deleted, updated_source_with_net_arr_logic.last_activity_date, updated_source_with_net_arr_logic.sales_last_activity_date, updated_source_with_net_arr_logic.record_type_id, updated_source_with_net_arr_logic.dbt_scd_id, updated_source_with_net_arr_logic.dbt_updated_at, updated_source_with_net_arr_logic.dbt_valid_from, updated_source_with_net_arr_logic.dbt_valid_to, opportunity_deal_size, arr_created_date_id, created_date_id, sales_accepted_date_id, close_date_id, stage_0_pending_acceptance_date_id, stage_1_discovery_date_id, stage_2_scoping_date_id, stage_3_technical_evaluation_date_id, stage_4_proposal_date_id, stage_5_negotiating_date_id, stage_6_awaiting_signature_date_id, stage_6_closed_won_date_id, stage_6_closed_lost_date_id, technical_evaluation_date_id, last_activity_date_id, sales_last_activity_date_id, subscription_start_date_id, subscription_end_date_id, sales_qualified_date_id, dim_crm_opportunity_id, dim_crm_user_id, dim_crm_account_id, dim_parent_crm_opportunity_id, arr_created_date, crm_opp_owner_geo_stamped, crm_opp_owner_region_stamped, crm_opp_owner_area_stamped, crm_opp_owner_business_unit_stamped, raw_net_arr, order_type, opportunity_term_base, days_since_last_activity, created_date, sales_accepted_date, close_date, days_in_stage, close_fiscal_year, net_new_source_categories, source_buckets, deal_path, sales_qualified_source, sales_qualified_source_grouped, sqs_bucket_engagement, order_type_grouped, growth_type, user_segment_stamped, user_segment_region_stamped_grouped, user_segment_geo_region_area_stamped, crm_opp_owner_sales_segment_stamped, user_segment_stamped_grouped, crm_opp_owner_sales_segment_geo_region_area_stamped, sao_crm_opp_owner_sales_segment_stamped_grouped, sao_crm_opp_owner_segment_region_stamped_grouped, sales_segment, parent_segment, division_sales_segment_stamped, channel_type, is_open, is_risky, is_stage_1_plus, is_stage_3_plus, is_stage_4_plus, is_lost, is_renewal, is_duplicate, is_comp_new_logo_override, is_closed_deals, closed_buckets, sdr_or_bdr, reason_for_loss_staged, reason_for_loss_calc, stage_name_3plus, stage_name_4plus, competitors_other_flag, competitors_gitlab_core_flag, competitors_none_flag, competitors_github_enterprise_flag, competitors_bitbucket_server_flag, competitors_unknown_flag, competitors_github_flag, competitors_gitlab_flag, competitors_jenkins_flag, competitors_azure_devops_flag, competitors_svn_flag, competitors_bitbucket_flag, competitors_atlassian_flag, competitors_perforce_flag, competitors_visual_studio_flag, competitors_azure_flag, competitors_amazon_code_commit_flag, competitors_circleci_flag, competitors_bamboo_flag, competitors_aws_flag, _last_dbt_run.
>   compiled code at target/run/gitlab_snowflake/models/common_prep/restricted_safe/prep_crm_opportunity_calcs.sql
> ```

Fixed.

**Review by Vedin — APPROVED** [review]

**Review by Vedin — APPROVED** [review]
