### PR TITLE
Fix iceberg catalog 

### LINKED ISSUE #349: Restore iceberg catalog endpoints

### PR DESCRIPTION
**Pull request by osipovartem**
- fixed iceberg-rust [optional table commit fields](https://github.com/Embucket/iceberg-rust/pull/22)
- fixed path for metadata location during iceberg table update
- fixed AssertRefSnapshotId check
- fixed panic with missing tokio runtime timers
- fixed missing object store for external tables
Closes #349

### CODE REVIEW

**Review by Vedin — APPROVED** [review]

File: crates/runtime/src/execution/query.rs [hunk 1]
```diff
@@ -910,23 +910,7 @@ impl IceBucketQuery {
...
-                    .execute_logical_plan(plan)
-                    .await
-                    .context(super::error::DataFusionSnafu)?
-                    .collect()
-                    .await
-                    .context(super::error::DataFusionSnafu)
-            })
-            .await
-            .context(super::error::JobSnafu)??;
-        Ok(stream)
```
Comment (DanCodedThis) [inline crates/runtime/src/execution/query.rs:929]: Is this removal correct?

**Review by DanCodedThis — APPROVED** [review]
Other than that (which would be blocking), LGTM

File: crates/runtime/src/execution/query.rs (hunk 1 above)
Comment (osipovartem) [reply crates/runtime/src/execution/query.rs:929]: Yes, this code was duplicated
