### PR TITLE
engine: `rlike` & `regexp` exprs

### LINKED ISSUE #639: engine: Missing expression `rlike`
**Function:** `rlike`
**Category:** Regular expressions
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/rlike

**Test SQL:**
```sql
SELECT 'snowflake' RLIKE 'snow.*';
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT 'snowflake' RLIKE 'snow.*';
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: This feature is not implemented: Unsupported ast node in sqltorel: RLike {    │
│ negated: false, expr: Value(SingleQuotedString("snowflake")), pattern: Value(SingleQuotedString("snow.*")),  │
│ regexp: false }                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #574

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #639 & #640

**:tada: Regular expression 100% compatibility**

- [x] `regexp` expr impl
- [x] `rlike` expr impl
- [x] Uses a simple AST Rewriter
- [x] Docs
- [x] Insta tests
- [x] SLT tests
- [x] Visitor unit tests

P.S. Small `rlike` function fix in the rewriter. Also, we'll need to fix the backslashes in the near future for all string expressions.

Reference:
- https://docs.snowflake.com/en/sql-reference/functions/rlike
- https://docs.snowflake.com/en/sql-reference/functions/regexp

### CODE REVIEW

File: crates/embucket-functions/src/visitors/rlike_regexp_expr_rewriter.rs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    Expr, FunctionArg, FunctionArgExpr, FunctionArgumentList, FunctionArguments, Ident, ObjectName,
+    Statement, VisitorMut,
+};
+use datafusion_expr::sqlparser::ast::{Function, VisitMut};
+use std::ops::ControlFlow;
+
+#[derive(Debug, Default)]
+pub struct RLikeRegexpExprRewriter;
+
+impl VisitorMut for RLikeRegexpExprRewriter {
```
Comment (osipovartem) [inline crates/embucket-functions/src/visitors/rlike_regexp_expr_rewriter.rs:40]: Add comment for the visitor

**Review by osipovartem — APPROVED** [review]

**Review by osipovartem — APPROVED** [review]
