### PR TITLE
Use snowflake dialect from env

### LINKED ISSUE #166: sqlparser: TokenizerError error when trying to insert records with single quote
Rows example
```csv
Korea (Democratic People's Republic of)
Côte d'Ivoire
Lao People's Democratic Republic
```
dbt preparing insert in format 

```sql
create table datasets.test (c varchar);
insert datasets.test (c) values('Lao People\'s Democratic Republic');
```
Last statement triggers 
```
Execution error: DataFusion error: SQL error: TokenizerError("Unterminated string literal at Line: 1, Column: 67"
```

### PR DESCRIPTION
**Pull request by osipovartem**
Closes Embucket/control-plane-v2#166

### CODE REVIEW

**Review by DanCodedThis — APPROVED** [review]

File: crates/control_plane/src/service.rs [hunk 1]
```diff
@@ -227,8 +228,14 @@ impl ControlService for ControlServiceImpl {
             object_store,
         );
         let catalog = IcebergCatalog::new(Arc::new(rest_client), None).await?;
+        let sql_parser_dialect =
+            env::var("SQL_PARSER_DIALECT").unwrap_or_else(|_| "snowflake".to_string());
```
Comment (eadgbear) [inline crates/control_plane/src/service.rs:232]: Not sure I agree with this. We're putting in so much effort to support Snowflake-only syntax, why bother supporting anything else?

Comment (osipovartem) [reply crates/control_plane/src/service.rs:232]: let's switch to snowflake

Comment (rampage644) [reply crates/control_plane/src/service.rs:232]: I would still have this supported even perhaps on the request-level, with a default for snowflake dialect. Previously, snowflake dialect was a bit stricter than generic.

Comment (osipovartem) [reply crates/control_plane/src/service.rs:232]: So let's keep a flag from env with default to snowflake if not exist

**Review by rampage644 — APPROVED** [review]
