### PR TITLE
Try to cast to utf8 for if the type is numeric in lenght func

### LINKED ISSUE #1698: Function 'length' failed to match any signature
```Error during planning: Internal error: Function 'length' failed to match any signature, errors: Internal error: Expect TypeSignatureClass::Native(LogicalType(Native(String), String))```

### PR DESCRIPTION
**Pull request by osipovartem**
Closes #1698

### CODE REVIEW

File: crates/embucket-functions/src/string-binary/length.rs [hunk 1]
```diff
@@ -44,17 +41,10 @@ impl LengthFunc {
...
-                        TypeSignatureClass::Native(logical_string()),
-                    )]),
-                    TypeSignature::Coercible(vec![Coercion::new_exact(
-                        TypeSignatureClass::Native(logical_binary()),
-                    )]),
-                ],
-                Volatility::Immutable,
-            ),
+            signature: Signature {
+                type_signature: TypeSignature::Any(1),
```
Comment (Vedin) [inline crates/embucket-functions/src/string-binary/length.rs:45]: Probably, not important for this function but in general I prefer using `Signature::user_defined(Immutable)` and then implement `coerce_types` itself.

**Review by Vedin — APPROVED** [review]

File: crates/embucket-functions/src/string-binary/length.rs [hunk 2]
```diff
@@ -141,6 +131,16 @@ impl ScalarUDFImpl for LengthFunc {
                     .collect::<UInt64Array>();
                 Arc::new(new_array)
             }
+            v if v.is_numeric() => {
+                let casted = cast(&arr, &DataType::Utf8)?;
+                let strs = as_string_array(&casted)?;
+                let new_array = strs
+                    .iter()
+                    .map(|array_elem| array_elem.map(|value| value.chars().count() as u64))
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/string-binary/length.rs]: Why not just `value.len()`? Chars count, means we make an iterator and collect the length by using next until we get to None. Essentially, one is constant time O(1) and the second one is O(n).

File: crates/embucket-functions/src/string-binary/length.rs [hunk 3]
```diff
@@ -141,6 +131,16 @@ impl ScalarUDFImpl for LengthFunc {
...
+                    .collect::<UInt64Array>();
+                Arc::new(new_array)
+            }
+            DataType::Null => Arc::new((0..arr.len()).map(|_| None).collect::<UInt64Array>()),
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/string-binary/length.rs]: Is there `UInt64Array::new_nulls`? It's probably faster, since it wouldn't use an iterator, I think it would just write out the buffer.

**Review by DanCodedThis — APPROVED** [review]
@osipovartem LGTM

**Review by DanCodedThis — APPROVED** [review]
