### PR TITLE
[BUG] 629: implement missing insert function

### LINKED ISSUE #629: [BUG] Missing function: insert
**Function:** `insert`
**Category:** String & binary
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/insert

**Test SQL:**
```sql
SELECT INSERT('abcdef', 3, 2, 'XX');
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT INSERT('abcdef', 3, 2, 'XX');
```

**Stderr:**
```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'insert'.                                                                            │
│ Did you mean 'instr'?                                                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #576

### PR DESCRIPTION
**Pull request by AmosAidoo**
## Which issue does this PR close?

- Closes #629 

## Changes

- Added a new scalar udf, `Insert` and implemented logic according to snowflake docs
- Added a new macro, adopted from itertools at [https://docs.rs/itertools/latest/src/itertools/lib.rs.html#321-360](https://docs.rs/itertools/latest/src/itertools/lib.rs.html#321-360) to zip multiple iterators. It was useful for the current task.

## How was this tested?

- Added automated tests to validate functionality
- All existing tests pass

### CODE REVIEW

File: crates/df-builtins/src/insert.rs [hunk 1]
```diff
@@ -0,0 +1,333 @@
...
+        Self::new()
+    }
+}
+
+impl Insert {
+    pub fn new() -> Self {
+        Self {
+            signature: Signature::exact(
+                vec![
+                    DataType::Utf8,
```
Comment (Vedin) [inline crates/df-builtins/src/insert.rs]: I have some doubts about this. I believe we want to have signature for DataType::Binary here as well. Even datafusion currently doesn't support binary datatype it supports Binary values. So, something like this should work:
`select INSERT(X'1234567890ABCDEF', 4, 2, X'FFFF');`
with the result:
`123456ffffabcdef`

**Review by Vedin — CHANGES_REQUESTED** [review]
Great! I didn't verify macros logic but in general looks good to me. I'd only ask to verify it works with Binary as well.

File: crates/df-builtins/src/insert.rs (hunk 1 above)
Comment (AmosAidoo) [reply crates/df-builtins/src/insert.rs]: Thank you very much for the review. I have handled the binary case and updated the tests

**Review by Vedin — APPROVED** [review]

**Comment by AmosAidoo** [comment]
I have resolved the merge conflict

**Review by Vedin — APPROVED** [review]
