### PR TITLE
[BUG] 681: Implement rtrimmed_length function

### LINKED ISSUE #681: [BUG] Missing function: rtrimmed_length
**Function:** `rtrimmed_length`
**Category:** String & binary
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/rtrimmed_length

**Test SQL:**
```sql
SELECT RTRIMMED_LENGTH('  Snowflake  ');
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT RTRIMMED_LENGTH('  Snowflake  ');
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'rtrimmed_length'.                    │
│ Did you mean 'octet_length'?                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #576

### PR DESCRIPTION
**Pull request by AmosAidoo**
## Which issue does this PR close?

- Closes #681 

## Changes

- Added a new scalar udf, `RTrimmedLengthFunc` and implemented logic according to snowflake docs

## How was this tested?

- Added automated test to validate functionality
- All existing tests pass

### CODE REVIEW

File: crates/df-builtins/src/rtrimmed_length.rs [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+              (''),
+              ('ABC'),
+              (NULL);
+          ";
+        ctx.sql(insert).await?.collect().await?;
+
+        let q = "SELECT RTRIMMED_LENGTH(s) FROM test_strings;";
+        let result = ctx.sql(q).await?.collect().await?;
+
+        assert_batches_eq!(
```
Comment (osipovartem) [inline crates/df-builtins/src/rtrimmed_length.rs:100]: According to snowflake examples
https://docs.snowflake.com/en/sql-reference/functions/rtrimmed_length
```
SELECT RTRIMMED_LENGTH(' ABCD ');

+---------------------------+
| RTRIMMED_LENGTH(' ABCD ') |
|---------------------------|
|                         5 |
+---------------------------+
```
In the test it has 6 by some reason

File: crates/df-builtins/src/rtrimmed_length.rs [hunk 2]
```diff
@@ -0,0 +1,118 @@
+use datafusion::arrow::{array::UInt64Array, datatypes::DataType};
+use datafusion::error::Result as DFResult;
+use datafusion_common::cast::as_string_array;
+use datafusion_expr::{ColumnarValue, ScalarFunctionArgs, ScalarUDFImpl, Signature, Volatility};
+use std::any::Any;
+use std::sync::Arc;
+
+// rtrimmed_length SQL function
+// Returns the length of its argument, minus trailing whitespace, but including leading whitespace.
```
Comment (osipovartem) [inline crates/df-builtins/src/rtrimmed_length.rs:9]: Remove duplicated description

**Review by ravlio — APPROVED** [review]

**Review by ravlio — APPROVED** [review]

**Review by osipovartem — APPROVED** [review]

File: crates/df-builtins/src/rtrimmed_length.rs [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+        let arr = match &args[0] {
+            ColumnarValue::Array(arr) => arr,
+            ColumnarValue::Scalar(v) => &v.to_array()?,
+        };
+
+        let strs = as_string_array(&arr)?;
+
+        let new_array = strs
+            .iter()
+            .map(|array_elem| array_elem.map(|value| value.trim_end().len() as u64))
```
Comment (Vedin) [inline crates/df-builtins/src/rtrimmed_length.rs]: We can't use trim_end() here because we currently try to follow Snowflake implementations of such methods. [Snowflake implementation](https://docs.snowflake.com/en/sql-reference/functions/rtrimmed_length) of `rtrimmed_length` is `Equivalent to {fn LENGTH(str)} in ODBC`, which is 

> Returns the number of characters in string_exp, excluding trailing blanks. [https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/string-functions?view=sql-server-ver16](url)

For the strings `"ABCDEFGH  \t"` and `"ABCDEFGH  \n"` expected result is `11` but current implementation will return `8`.

**Review by Vedin — CHANGES_REQUESTED** [review]
@AmosAidoo Thank you for your contribution! Overall looks good! I asked for one adjustment to make this function work the same as in Snowflake, and add such cases to tests as well.

**Review by Vedin — APPROVED** [review]

File: crates/df-builtins/src/rtrimmed_length.rs [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+
+        let insert = r"
+          INSERT INTO test_strings VALUES 
+              ('  ABCD  '),
+              ('   ABCDEFG'),
+              ('ABCDEFGH  '),
+              ('   '),
+              (''),
+              ('ABC'),
+              (E'ABCDEFGH  \t'),
```
Comment (rampage644) [inline crates/df-builtins/src/rtrimmed_length.rs:92]: WHat is the `E` prefix here?

**Review by rampage644 — APPROVED** [review]
looks good - can merge after rebase!

**Comment by AmosAidoo** [comment]
@osipovartem I am done with the rebase.

**Review by Vedin — APPROVED** [review]
