### PR TITLE
Parse current ip address for current_ip_address() func

### LINKED ISSUE #970: [BUG] Missing current_ip_address
**Function:** `current_ip_address `
**Category:** Context
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/current_ip_address

**Test SQL:**
```sql
SELECT CURRENT_IP_ADDRESS();
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
SELECT CURRENT_IP_ADDRESS();
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'current_ip_address'.                     │
│ Did you mean 'current_database'?                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #571

### PR DESCRIPTION
**Pull request by osipovartem**
Closes #970

Implementation for current_ip_address func
https://docs.snowflake.com/en/sql-reference/functions/current_ip_address

### CODE REVIEW

File: crates/api-snowflake-rest/src/handlers.rs [hunk 1]
```diff
@@ -93,6 +94,7 @@ fn records_to_json_string(recs: &[RecordBatch]) -> Result<String, DbtError> {
 
 #[tracing::instrument(level = "debug", skip(state, body), err, ret(level = tracing::Level::TRACE))]
 pub async fn query(
+    ConnectInfo(addr): ConnectInfo<SocketAddr>,
```
Comment (rampage644) [inline crates/api-snowflake-rest/src/handlers.rs:97]: What if we move it even out of handlers and instead get it during app initialization?

Comment (osipovartem) [reply crates/api-snowflake-rest/src/handlers.rs:97]: This is related to client IP, not server, so each request should be handled separately 
Also ConnectInfo is just like headers info, specific for each request.

**Review by rampage644 — APPROVED** [review]
