### PR TITLE
Fix IPC arrow format issue

### LINKED ISSUE #115: api: switch from JSON data type to ARROW IPC
[Branch](https://github.com/Embucket/control-plane-v2/tree/issues/115_switch_to_arrow_ipc)

Snowflake converter for FIXED datatype via arrow ipc natively supports: int8, int16, int32, int64, DECIMAL128 and no uint types at all:
https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp#L173

### PR DESCRIPTION
**Pull request by osipovartem**
- the issue was in NULL type that we send for **NULL as comment**
- NULL type was fixed
- Arrow IPC format [expects](https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp#L268-L293) all timestamps in i64 format with scale, for example 1627846261233222 scale 6
- JSON format [expects](https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/converter.py#L769-L781) all timestamps in string format with point delimiter with scale, for example "1627846261.233222" scale 6
- Moved DBT_FORMAT to env variable with json default

Closes #115 and #67

### CODE REVIEW

File: crates/control_plane/src/utils.rs [hunk 1]
```diff
@@ -9,7 +9,45 @@ use chrono::DateTime;
...
+        match self {
+            Self::Arrow => write!(f, "arrow"),
+            Self::Json => write!(f, "json"),
+        }
+    }
+}
+
+impl SerializationFormat {
+    fn new() -> Self {
+        let var = env::var("DBT_SERIALIZATION_FORMAT").unwrap_or_else(|_| "json".to_string());
```
Comment (Vedin) [inline crates/control_plane/src/utils.rs:44]: do we need to use `to_lowercase()` here, or do we always expect it to be in lowercase already?

**Review by DanCodedThis — APPROVED** [review]
LGTM, you checked the https://github.com/Embucket/icebucket/issues/67?

File: crates/control_plane/src/utils.rs [hunk 2]
```diff
@@ -87,58 +127,95 @@ pub fn convert_record_batches(
...
+fn convert_timestamp_to_struct(
+    column: &ArrayRef,
+    unit: TimeUnit,
+    ser: SerializationFormat,
+) -> ArrayRef {
+    match ser {
+        SerializationFormat::Arrow => {
+            let timestamps: Vec<_> = match unit {
+                TimeUnit::Second => column
+                    .as_any()
```
Comment (Vedin) [inline crates/control_plane/src/utils.rs]: I'm not sure what's a best practice here but personally don't like repeating:
```
.as_any()
.downcast_ref::<TimestampMillisecondArray>()
.unwrap()
.iter()
.collect(),
```
Maybe introduce some macro or generic type to avoid this? I'm talking about smth like this:
```rust
macro_rules! downcast_timestamp {
    ($column:expr, $array_type:ty) => {
        $column
            .as_any()
            .downcast_ref::<$array_type>()
            .unwrap()
            .iter()
    };
}
```

Comment (eadgbear) [reply crates/control_plane/src/utils.rs]: We could implement `TryInto` or something similar to skip the steps, but it would just be moving the code elsewhere
