### PR TITLE
Snowflake error regression tests for drop table, alter table

### LINKED ISSUE #1557: Snowflake error regression in `drop table`
### Regression error of recently added snowflake error for `drop table`

With error fix regression test should be added as well

### PR DESCRIPTION
**Pull request by YaroslavLitvinov**
closes #1557

Add complete set of snowflake error tests checking existence errors texts for drop table, alter table

### CODE REVIEW

File: crates/core-executor/src/error.rs [hunk 1]
```diff
@@ -186,6 +186,15 @@ pub enum Error {
         location: Location,
     },
 
+    #[snafu(display("Table {table} not found in schema {schema} in database {db}"))]
+    TableNotFoundInSchemaInDatabase {
```
Comment (osipovartem) [inline crates/core-executor/src/error.rs:191]: The error above is not used (TableNotFound)
Let's reuse/update/delete

File: crates/core-executor/src/query.rs [hunk 2]
```diff
@@ -541,6 +551,60 @@ impl UserQuery {
...
     }
 
+    #[instrument(
+        name = "UserQuery::alter_table_query",
+        level = "trace",
+        skip(self),
+        err
+    )]
+    #[allow(clippy::too_many_lines)]
+    pub async fn alter_table_query(&self, statement: Statement) -> Result<QueryResult> {
```
Comment (osipovartem) [inline crates/core-executor/src/query.rs]: check this PR https://github.com/Embucket/embucket/pull/1564
we don't need iceberg catalog here

File: crates/core-executor/src/error.rs (hunk 1 above)
Comment (YaroslavLitvinov) [reply crates/core-executor/src/error.rs:191]: This actually was used in drop table, now I added alter table as well

**Review by DanCodedThis — APPROVED** [review]
@YaroslavLitvinov LGTM, but do check iceberg catalog as @osipovartem said

File: crates/core-executor/src/query.rs (hunk 2 above)
Comment (YaroslavLitvinov) [reply crates/core-executor/src/query.rs]: @osipovartem  I wonder why iceberg catalog needed in drop table, but in alter table it is not needed

File: crates/core-executor/src/error.rs [hunk 3]
```diff
@@ -187,6 +187,15 @@ pub enum Error {
         location: Location,
     },
 
+    #[snafu(display("Table {table} not found in schema {schema} in database {db}"))]
```
Comment (rampage644) [inline crates/core-executor/src/error.rs]: `Table {table} not found in {db}.{schema}`

**Review by rampage644 — APPROVED** [review]

File: crates/core-executor/src/query.rs [hunk 4]
```diff
@@ -566,9 +566,10 @@ impl UserQuery {
                 .table(&resolved.table)
                 .await
                 .context(ex_error::DataFusionSnafu)?
-                .context(ex_error::TableNotFoundSnafu {
+                .context(ex_error::TableNotFoundInSchemaInDatabaseSnafu {
                     table: &resolved.table.to_string(),
                     schema: &resolved.schema.to_string(),
+                    db: &resolved.catalog.to_string(),
                 })?;
         }
```
Comment (DanCodedThis) [inline crates/core-executor/src/query.rs:574]: This here can be (since we don't really have a specific first `.context()` error):
```rust
let Ok(Some(_)) = schema
                .table(&resolved.table)
                .await else {
                    return ex_error::TableNotFoundInSchemaInDatabaseSnafu {
                        table: &resolved.table.to_string(),
                        schema: &resolved.schema.to_string(),
                        db: &resolved.catalog.to_string(),
                }.fail()?;
            };
```

Did I already suggest this (seems like a déjà vu)?

**Review by DanCodedThis — APPROVED** [review]
@YaroslavLitvinov LGTM
