### PR TITLE
Many auth DedicatedExecutors fix

### LINKED ISSUE #1290: Embucket opens to many sessions
Root cause: Embucket consumes all the available file descriptors when creating new sessions, and finally fail creating new sessions when no more files can't be opened. It depends on environment, how many FD can be opened, so probably you need run repro more times or change it increasing numbers. 

After 3 minutes or so Embucket recovers and works as usual!

### Snippet from embucketd log after it failed to open new session
```
---- tests::test_seed_client stdout ----

thread 'DedicatedExecutor driver' panicked at crates/core-executor/src/dedicated_executor.rs:600:22:
Creating tokio runtime: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_seed_client' panicked at crates/core-executor/src/dedicated_executor.rs:627:39:
driver started: RecvError

thread 'tests::test_seed_client' panicked at crates/embucket-seed/src/requests/http.rs:88:24:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "http://0.0.0.0:40053/ui/queries", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }


failures:
    tests::test_seed_client
```

### Ways to reproduce
``` bash
# using snowsql
for i in {1..100}; do (snow sql -c local-embucket-bad-pass -q "SELECT 1" &) ; done

#   using api-ui
for i in {1..100}; do (python -c "import requests; requests.request('post', 'http://localhost:3000/ui/auth/login')" &) ; done  
```

Update:
Previous approach `cargo embucket-seed` can't be used as a repro anymore, after merging PR https://github.com/Embucket/embucket/pull/1329 that supports new session_id cookie.

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #1290 

- Removed Extractor from `login` in `snowflake-rest` and `api-ui` auths to not call the session generation before log in.
- Also removed Extractor from `refresh_token` in `api-ui`.
- Removed `tower_session` layer since it was used just as a gimmick to get to execution service through a trait. 
- Instead, added an `ExecutionAppState` trait for getting `execution_svc` from any AppState that has it.
- As suggested by @YaroslavLitvinov removed session management from `api-ui` auth flow entirely. This resulted in a somewhat big rewrite (refactor). 
- However, this now means that session flow is completely self-contained, including, but not limited to: session generation, session cookie management, session extraction, etc.

### CODE REVIEW

File: crates/api-sessions/src/session.rs [hunk 1]
```diff
@@ -131,82 +57,78 @@ pub struct DFSessionId(pub String);
...
-                .context(SessionPersistSnafu)?;
-            session.set_expiry(Some(Expiry::OnInactivity(Duration::seconds(
-                SESSION_INACTIVITY_EXPIRATION_SECONDS,
-            ))));
-            session.save().await.context(SessionPersistSnafu)?;
-            Ok(Self(token))
-        //If the session is dead
+        let execution_svc = state.get_execution_svc();
+
+        if let Some(token) = extract_token_from_auth(&req.headers) {
```
Comment (YaroslavLitvinov) [inline crates/api-sessions/src/session.rs:68]: What is extract_token_from_auth extracting SnowflakeToken (api-snowflake-rest) doing in DFSessionId extractor?

If that wasn't a mistake, such unobvious things worth a comment.

File: crates/api-ui/src/auth/error.rs [hunk 2]
```diff
@@ -95,6 +95,12 @@ pub enum Error {
         #[snafu(implicit)]
         location: Location,
     },
+
+    #[snafu(display("Execution error: {error}"))]
+    Execution {
```
Comment (YaroslavLitvinov) [inline crates/api-ui/src/auth/error.rs]: auth Execution error accidently added?

**Review by YaroslavLitvinov — APPROVED** [review]
LGTM, There are just two things I mentioned that may need fixes.

File: crates/api-ui/src/auth/error.rs (hunk 2 above)
Comment (DanCodedThis) [reply crates/api-ui/src/auth/error.rs]: Yep, it was from the first iteration I tried.

File: crates/api-sessions/src/session.rs (hunk 1 above)
Comment (DanCodedThis) [reply crates/api-sessions/src/session.rs:68]: I'll add a comment. Some explanation: this function is used in the **session.rs** itself. And it's used in the `require_auth` layer as part of the session flow in the **api-snowflake-rest**, but exporting the function from the **api-snowflake-rest** would create a cyclic dependency.

**Review by YaroslavLitvinov — APPROVED** [review]

**Review by YaroslavLitvinov — APPROVED** [review]

**Comment by DanCodedThis** [comment]
Unit-test flow can't run. I restarted, still it's stuck. No significant changes were done (last time it ran successfully), so I'm merging.
