### PR TITLE
Utoipa Spec Fixes for tables & auth

### LINKED ISSUE #725: api: UI No `Utoipa` spec for auth
- Spec: `/auth/login` POST
- Spec: `/auth/refresh` POST
- Spec: `/auth/logout` POST

### PR DESCRIPTION
**Pull request by DanCodedThis**
Closes #725

Also includes a minor fix for tables spec

### CODE REVIEW

File: crates/runtime/src/http/auth/handlers.rs [hunk 1]
```diff
@@ -163,6 +175,18 @@ pub async fn login(
...
 }
 
+#[utoipa::path(
+    post,
+    path = "/auth/refresh",
+    operation_id = "refresh",
+    tags = ["auth"],
+    responses(
+        (status = 200, description = "Successful Response", body = AuthResponse),
+        (status = 401, description = "Unauthorized", body = ErrorResponse),
```
Comment (YaroslavLitvinov) [inline crates/runtime/src/http/auth/handlers.rs:214]: OAS of Unauthorized response should include www-authenticate header

**Comment by YaroslavLitvinov** [comment]
Now, every handler now can return Unauthorized status code with www-authenticate header in response, and we need to update spec for every handler too. Better doing it in some programmatic way if possible in opposite to adding utoipa macroses manually into multiple places in code.

**Comment by DanCodedThis** [comment]
> Now, every handler now can return Unauthorized status code with www-authenticate header in response, and we need to update spec for every handler too. Better doing it in some programmatic way if possible in opposite to adding utoipa macroses manually into multiple places in code.

Could've used RustRover's builtin smart find refactor for the directory of ui, but already did it manually

**Review by nikitastryuk — APPROVED** [review]

File: crates/runtime/src/http/auth/handlers.rs [hunk 2]
```diff
@@ -128,6 +130,29 @@ fn set_cookies(headers: &mut HeaderMap, refresh_token: &str) -> AuthResult<()> {
...
+        login,
+        refresh_access_token,
+        logout,
+    ),
+    components(
+        schemas(
+            LoginPayload,
+            AuthResponse,
+            RefreshTokenResponse,
+            Claims,
```
Comment (YaroslavLitvinov) [inline crates/runtime/src/http/auth/handlers.rs]: Claims is not intended to be used in OAS, we don't return it.

File: crates/runtime/src/http/auth/models.rs [hunk 3]
```diff
@@ -35,7 +35,7 @@ pub struct LoginPayload {
     pub password: String,
 }
 
-#[derive(Serialize, Deserialize)]
+#[derive(Serialize, Deserialize, Clone, PartialEq, Eq, ToSchema)]
```
Comment (YaroslavLitvinov) [inline crates/runtime/src/http/auth/models.rs]: remove Clone, PartialEq, Eq, ToSchema from Claims

**Review by YaroslavLitvinov — CHANGES_REQUESTED** [review]

File: crates/runtime/src/http/auth/handlers.rs (hunk 1 above)
Comment (DanCodedThis) [reply crates/runtime/src/http/auth/handlers.rs:214]: > OAS of Unauthorized response should include www-authenticate header

@YaroslavLitvinov like this? (did some changes, plz recheck)

File: crates/runtime/src/http/auth/models.rs (hunk 3 above)
Comment (YaroslavLitvinov) [reply crates/runtime/src/http/auth/models.rs]: From this:
```
[derive(Serialize, Deserialize, Clone, PartialEq, Eq, ToSchema)]
```

to this::
```
[derive(Serialize, Deserialize)]
```

File: crates/runtime/src/http/auth/handlers.rs (hunk 1 above)
Comment (YaroslavLitvinov) [reply crates/runtime/src/http/auth/handlers.rs:214]: ~Claims still in spec, no it removed.~ No Claims - ok. Probably something didn't refresh

File: crates/runtime/src/http/auth/handlers.rs [hunk 4]
```diff
@@ -196,6 +249,17 @@ pub async fn refresh_access_token(
     }
 }
 
+#[utoipa::path(
+    post,
+    path = "/auth/logout",
+    operation_id = "logout",
+    tags = ["auth"],
+    responses(
+        (status = 200, description = "Successful Response", body = AuthResponse),
```
Comment (YaroslavLitvinov) [inline crates/runtime/src/http/auth/handlers.rs]: logout doesn't return AuthResponse, just empty

**Review by YaroslavLitvinov — CHANGES_REQUESTED** [review]

**Review by YaroslavLitvinov — APPROVED** [review]
