### PR TITLE
boolor_agg aggregate function

### LINKED ISSUE #548: Add `boolor_agg`

### LINKED ISSUE #660: [BUG] Missing function: boolor
**Function:** `boolor`
**Category:** Aggregate
**Status:** Failed (Return Code: 1)
**Documentation:** https://docs.snowflake.com/en/sql-reference/functions/boolor

**Test SQL:**
```sql
WITH bools AS (SELECT TRUE AS val UNION ALL SELECT FALSE AS val) SELECT BOOLOR(val) FROM bools;
```

**Expected Result:**
```
N/A
```

**Actual Result:**
```
WITH bools AS (SELECT TRUE AS val UNION ALL SELECT FALSE AS val) SELECT BOOLOR(val) FROM bools;
```

**Stderr:**
```
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 000200: 200: DataFusion error: Error during planning: Invalid function 'boolor'.                             │
│ Did you mean 'bool_or'?                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Parent EPIC:** #514

### PR DESCRIPTION
**Pull request by ravlio**
Closes #548

### CODE REVIEW

File: crates/runtime/src/execution/datafusion/functions/aggregate/mod.rs [hunk 1]
```diff
@@ -1,13 +1,15 @@
...
 mod booland_agg;
+mod boolor_agg;
 
 pub fn register_udafs(registry: &mut dyn FunctionRegistry) -> datafusion_common::Result<()> {
-    let functions: Vec<Arc<AggregateUDF>> = vec![Arc::new(AggregateUDF::from(
-        booland_agg::BoolAndAggUDAF::new(),
-    ))];
+    let functions: Vec<Arc<AggregateUDF>> = vec![
+        Arc::new(AggregateUDF::from(booland_agg::BoolAndAggUDAF::new())),
+        Arc::new(AggregateUDF::from(booland_agg::BoolAndAggUDAF::new())),
```
Comment (Vedin) [inline crates/runtime/src/execution/datafusion/functions/aggregate/mod.rs]: Shouldn't it be `boolor_agg`?

**Review by Vedin — APPROVED** [review]

**Review by rampage644 — APPROVED** [review]
lgtm after BoolAndAgg -> BoolOrAgg
