### PR TITLE
Fix datediff, last_day, dayofweek funcs

### LINKED ISSUE #1512: Fix datediff func to allow arrays

### PR DESCRIPTION
**Pull request by osipovartem**
- Fixed datediff to take into account Snowflake logic
- Fixed DAY to return correct number of days
- Fixed DAYOFWEEK to take into account WEEK_START 
- Fixed LAST_DAY to take into account WEEK_START 
- Fixed MONTHNAME slts
- Fixed date_part_extract WEEK_START
Closes #1512

### CODE REVIEW

File: crates/embucket-functions/src/datetime/last_day.rs [hunk 1]
```diff
@@ -54,8 +57,73 @@ impl LastDayFunc {
...
         }
     }
+
+    #[must_use]
+    pub fn week_start(&self) -> u32 {
+        self.session_params
+            .get_property("week_start")
+            .unwrap_or_else(|| "0".to_string())
+            .parse::<u32>()
+            .unwrap_or(0)
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/datetime/last_day.rs]: This could be one `.map_or_else()` if you get the value - parse, if no - no need to parse a string `"0"` and unwrap to `0` on it.

File: crates/embucket-functions/src/datetime/last_day.rs [hunk 2]
```diff
@@ -54,8 +57,73 @@ impl LastDayFunc {
...
+                    0
+                } else {
+                    (week_start - 1) % 7
+                };
+                let last_day_num = (week_start_norm + 6) % 7;
+                let weekday_num = date.weekday().num_days_from_monday();
+
+                let days_until_week_end = (last_day_num + 7 - weekday_num) % 7;
+                let last_day_of_week = date + Duration::days(days_until_week_end.into());
+                last_day_of_week.and_hms_opt(0, 0, 0).unwrap()
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/datetime/last_day.rs]: `use snafu::OptExt` + `.context()` on the Option.

File: crates/embucket-functions/src/datetime/last_day.rs [hunk 3]
```diff
@@ -54,8 +57,73 @@ impl LastDayFunc {
...
+    #[allow(
+        clippy::unwrap_used,
+        clippy::as_conversions,
+        clippy::cast_possible_truncation
+    )]
+    fn last_day(&self, date: &NaiveDateTime, date_part: &str) -> DFResult<NaiveDateTime> {
+        let date = date.date();
+
+        let new_date = match date_part.to_lowercase().as_str() {
+            "day" => date.and_hms_opt(0, 0, 0).unwrap(),
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/datetime/last_day.rs]: use snafu::OptExt + .context() on the Option. And anywhere similar or also have a reasonable default.

File: crates/embucket-functions/src/datetime/last_day.rs [hunk 4]
```diff
@@ -54,8 +57,73 @@ impl LastDayFunc {
...
+                let (next_year, next_month) = if month == 12 {
+                    (year + 1, 1)
+                } else {
+                    (year, month + 1)
+                };
+
+                let last_day = NaiveDate::from_ymd_opt(next_year, next_month, 1)
+                    .unwrap()
+                    .pred_opt()
+                    .unwrap();
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/datetime/last_day.rs]: use snafu::OptExt + .context() on the Option.

File: crates/embucket-functions/src/datetime/last_day.rs [hunk 5]
```diff
@@ -54,8 +57,73 @@ impl LastDayFunc {
...
+
+                last_day.and_hms_opt(0, 0, 0).unwrap()
+            }
+            "year" => {
+                let year = date.year();
+                NaiveDate::from_ymd_opt(year, 12, 31)
+                    .unwrap()
+                    .and_hms_opt(0, 0, 0)
+                    .unwrap()
```
Comment (DanCodedThis) [inline crates/embucket-functions/src/datetime/last_day.rs]: use snafu::OptExt + .context() on the Option.

**Review by DanCodedThis — APPROVED** [review]
@osipovartem LGTM, some nitpicks

File: crates/embucket-functions/src/datetime/last_day.rs (hunk 3 above)
Comment (osipovartem) [reply crates/embucket-functions/src/datetime/last_day.rs]: This functionality was copy-pasted/moved

**Review by DanCodedThis — APPROVED** [review]
